src/styles/accounting_overview.scss, src/styles/inputs.scss, src/styles/view.scss, src/views/AccountingOverview/AccountingOverview.tsx
Improve responsiveness of components:
1. no new line in the select placeholder
2. add toggling of detailed PnL charts in Accounting Overview for mobile views
3. use font-size 16px in inputs on iPhone devices to prevent auto zoom in
4. view headers go into column layout on mobile devices
=> feat: improved rwd

src/components/ChartOfAccountsTable/ChartOfAccountsTable.tsx, src/components/ProfitAndLossSummaries/MiniChart.tsx, src/styles/accounting_overview.scss, src/styles/component.scss
1. Fix "Collpase" typo
2. Hide detailed charts toggle on desktop
3. mini charts sizing
=> fix: UI rwd fixes

src/contexts/LayerContext/LayerContext.tsx, src/hooks/useLinkedAccounts/useLinkedAccounts.ts, src/providers/LayerProvider/LayerProvider.tsx, src/types/layer_context.ts
Add usePlaidSandbox as an optional field in LayerProvider props
=> toggle plaid sandbox in layer provider

src/api/layer.ts, src/api/layer/tasks.ts, src/components/Badge/Badge.tsx, src/components/Journal/Journal.tsx, src/components/Tasks/Tasks.tsx, src/components/Tasks/index.tsx, src/components/TasksHeader/TasksHeader.tsx, src/components/TasksHeader/index.tsx, src/components/TasksList/TasksList.tsx, src/components/TasksList/index.tsx, src/components/TasksListItem/TasksListItem.tsx, src/components/TasksListItem/index.tsx, src/components/TasksPending/TasksPending.tsx, src/components/TasksPending/index.tsx, src/config/charts.ts, src/contexts/TasksContext/TasksContext.tsx, src/contexts/TasksContext/index.tsx, src/hooks/useTasks/index.tsx, src/hooks/useTasks/useTasks.tsx, src/icons/ProgressIcon.tsx, src/icons/SmileIcon.tsx, src/index.tsx, src/styles/index.scss, src/styles/tasks.scss, src/types/tasks.ts
https://github.com/Layer-Fi/layer-react/assets/32065451/8ae4846d-e260-4bbb-85b8-c8b0d934335f
=> feat: add tasks list

src/components/BankTransactionList/BankTransactionList.tsx
Fix missing props after rebase.
=> fix: bank transactions rebase

src/components/Toast/Toast.tsx, src/components/View/View.tsx, src/contexts/LayerContext/LayerContext.tsx, src/providers/LayerProvider/LayerProvider.tsx, src/types/layer_context.ts
Dismiss toast when user click on the toast.
=> feat: dismiss toast on click

src/components/Toast/Toast.tsx, src/components/View/View.tsx, src/contexts/LayerContext/LayerContext.tsx, src/providers/LayerProvider/LayerProvider.tsx, src/types/layer_context.ts, src/views/AccountingOverview/AccountingOverview.tsx
Toast state added to context layer.
=> context for notifications

src/components/Drawer/Drawer.tsx, src/components/Drawer/index.tsx, src/styles/drawer.scss, src/styles/index.scss, src/styles/variables.scss, src/views/AccountingOverview/AccountingOverview.tsx
Drawer component.
Used in Accounting Overview View - will be removed from there.
=> Drawer component

src/components/DateMonthPicker/DateMonthPicker.tsx, src/hooks/useWindowSize/index.ts, src/hooks/useWindowSize/useWindowSize.ts, src/styles/date_month_picker.scss
[LAY-727](https://linear.app/layerfi/issue/LAY-727/datemonthpicker-mobile-friendly)
https://github.com/Layer-Fi/layer-react/assets/32065451/3c835fef-07c6-4e4a-926a-82d0fef769aa
=> fix: date month picker

src/api/layer.ts, src/api/layer/bankTransactions.ts, src/api/layer/profit_and_loss.ts, src/components/BankTransactions/BankTransactionsHeader.tsx, src/components/ChartOfAccountsTable/ChartOfAccountsTable.tsx, src/components/View/View.tsx, src/styles/button.scss, src/types/general.ts, src/views/Reports/Reports.tsx
fixes: LAY-721
Also removes the non-functional download button on the GL page
=> Add csv download buttons to bank transactions and pnl

src/components/ProfitAndLossChart/ProfitAndLossChart.tsx, src/styles/charts.scss, src/styles/profit_and_loss.scss
Improvements on Profit And Loss chart:
1. uncategorized symbol in the legend
2. ticks colors of Y axis
3. the order of "0" Y axis line
=> feat: improved pnl chart styling

src/components/BankTransactionMobileList/BankTransactionMobileList.tsx, src/components/BankTransactionMobileList/BankTransactionMobileListItem.tsx, src/components/BankTransactionMobileList/TransactionToOpenContext.ts, src/components/BankTransactions/BankTransactions.tsx, src/components/Toast/Toast.tsx, src/hooks/useBankTransactions/useBankTransactions.tsx, src/styles/bank_transactions_mobile_list.scss
Improve transitions in the mobile list of Bank Transactions:
1. Open next item after saving previous one
2. Better loading logic
3. Remove item with animation on "To Review" list
=> feat: mobile bank transactions list - animations

src/components/LinkedAccountsInactive/LinkedAccountsInactive.tsx, src/styles/linked_accounts.scss
https://github.com/Layer-Fi/layer-react/assets/32065451/2230f337-d7eb-43d5-ad87-5202b0479950
=> fix: linked accounts

src/components/ProfitAndLossChart/ProfitAndLossChart.tsx, src/hooks/useProfitAndLoss/useProfitAndLossLTM.tsx
Show loading month when user is moving the chart window to the previous period.
Previously, we had a lag, because bar was shown "after" the data was loaded. Now, it show "loading" bar.
https://github.com/Layer-Fi/layer-react/assets/11715931/ca831ca9-ecbb-4ef3-aca2-b9ab9ca9207e
=> feat: show loading month on chart

src/components/BankTransactionList/BankTransactionListItem.tsx, src/components/BankTransactionMobileList/BusinessForm.tsx, src/components/BankTransactionMobileList/SplitForm.tsx, src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/types/categories.ts, src/utils/bankTransactions.ts
Use `accountId` in categorization by default and fallback to `stable_name`.
=> feat: support id-based categorization in categorization component

src/components/Input/DateInput.tsx, src/styles/datetime.scss
[639](https://linear.app/layerfi/issue/LAY-639/journal-datepicker-styling-react-datepicker)
https://github.com/Layer-Fi/layer-react/assets/32065451/e4ec5c94-5f1d-40ff-ab00-d8158b92d54f
=> Redesign datepicker

src/contexts/LayerContext/LayerContext.tsx, src/providers/LayerProvider/LayerProvider.tsx, src/styles/ledger_account.scss, src/styles/linked_accounts.scss, src/styles/profit_and_loss.scss, src/styles/profit_and_loss_detailed_charts.scss, src/types/layer_context.ts, src/utils/colors.ts
Fix using `dark color` instead of `--text-primary-color`.
Before:
<br />
<br />
After:
=> fix: use primary text color

package.json
Syncing this version with the actual published version in NPM. We had fallen behind here.
=> version 0.1.28

src/components/DateDayPicker/DateDayPicker.tsx, src/components/DateDayPicker/index.tsx
=> feat: add day picker

src/styles/bank_transactions.scss, src/styles/inputs.scss
Fix spacing in Bank Transactions table (category column)
=> fix: spacing in category column of bank transactions

src/components/BalanceSheet/BalanceSheet.tsx, src/components/JournalTable/JournalTable.tsx, src/components/LedgerAccount/LedgerAccountIndex.tsx, src/components/ProfitAndLossDatePicker/ProfitAndLossDatePicker.tsx
=> remove nonfunctional download buttons, rerender date picker

src/components/Onboarding/ConnectAccount.tsx, src/components/TransactionToReviewCard/TransactionToReviewCard.tsx, src/utils/bankTransactions.ts, src/views/AccountingOverview/AccountingOverview.tsx
=> show uncategorized txns for selected month

src/components/JournalEntryDetails/JournalEntryDetails.tsx, src/components/ProfitAndLossDetailedCharts/DetailedChart.tsx, src/components/ProfitAndLossDetailedCharts/ProfitAndLossDetailedCharts.tsx, src/styles/bank_transactions.scss, src/styles/component.scss, src/styles/index.scss, src/styles/panel.scss, src/styles/profit_and_loss.scss, src/styles/profit_and_loss_detailed_charts.scss, src/styles/reports.scss, src/views/Reports/Reports.tsx
Stick the sidebar content.
https://www.loom.com/share/1d78c260edc14bc496b9a420afe49162?sid=fb7d0a25-06d5-4f8a-a07f-8442c9a15177
=> fix: sidebar content positioning

src/components/ChartOfAccountsDatePicker/ChartOfAccountsDatePicker.tsx, src/components/DateMonthPicker/DateMonthPicker.tsx, src/components/ProfitAndLossDatePicker/ProfitAndLossDatePicker.tsx, src/styles/date_month_picker.scss
Fix the way we show date picker on some views.
=> fix: opt out from mobile version of date picker

src/components/JournalEntryDetails/JournalEntryDetails.tsx, src/components/LedgerAccount/LedgerAccountIndex.tsx, src/components/LedgerAccountEntryDetails/LedgerAccountEntryDetails.tsx, src/components/ProfitAndLossDetailedCharts/DetailedChart.tsx, src/components/ProfitAndLossDetailedCharts/ProfitAndLossDetailedCharts.tsx, src/styles/button.scss, src/styles/details_list.scss, src/styles/ledger_account.scss, src/styles/profit_and_loss_detailed_charts.scss, src/types/categories.ts
Standardize headings in sidebars.
=> fix: standarize sidebar headers

package-lock.json, src/components/PeriodPicker/PeriodPicker.tsx, src/components/PeriodPicker/index.tsx, src/styles/index.scss, src/styles/period_picker.scss, src/views/AccountingOverview/AccountingOverview.tsx
=> feat: period picker

src/styles/linked_accounts.scss
Fix sizing of "Add account" button in Linked account component.
=> fix: linked accounts - add account button size

src/styles/bank_transactions.scss
[LAY-803](https://linear.app/layerfi/issue/LAY-803/bank-transactions-date-picker)
=> fix: bank transactions picker

src/components/DatePicker/DatePicker.tsx, src/components/ProfitAndLossDatePicker/ProfitAndLossDatePicker.tsx, src/components/Tasks/Tasks.tsx, src/components/TasksHeader/TasksHeader.tsx, src/components/TasksList/TasksList.tsx, src/components/TasksPending/TasksPending.tsx, src/components/View/View.tsx, src/styles/bookkeeping_overview.scss, src/styles/panel.scss, src/styles/tasks.scss, src/views/BookkeepingOverview/BookkeepingOverview.tsx
[LAY-812](https://linear.app/layerfi/issue/LAY-812/bookkeeping-update)
https://github.com/user-attachments/assets/31e39b79-7d22-41b5-88bd-6c68235dc9ec
=> update: bookkeeping view

src/styles/bookkeeping_overview.scss, src/styles/tasks.scss
Fix tasks pagination.
https://github.com/user-attachments/assets/3b6f9ab6-42ef-41d1-8ff3-7a69a340e722
=> fix: tasks pagination

src/api/layer.ts, src/api/layer/quickbooks.ts, src/components/Quickbooks/Quickbooks.tsx, src/components/Quickbooks/index.tsx, src/hooks/useQuickbooks/index.ts, src/hooks/useQuickbooks/useQuickbooks.ts, src/index.tsx, src/types/quickbooks.ts
This PR includes:
1. Working OAuth linking/unlinking
2. Untested Quickbooks sync-from trigger
=> Quickbooks integration

src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/DatePickerOptions.tsx, src/styles/datepicker.scss
1. Fix selecting range of dates in date picker.
2. Fix highlighting
3. Add "Last year" and "Last quarter" options
https://github.com/user-attachments/assets/b4294ad2-c96c-4651-9d74-c81b66acb31a
=> fix: date picker range selection

src/components/ProfitAndLossChart/ProfitAndLossChart.tsx, src/types/profit_and_loss.ts
Show inverted expenses on pnl chart.
=> feat: use inverted expenses on pnl chart

package.json, src/providers/LayerProvider/LayerProvider.tsx
=> Add staging env

src/components/TransactionToReviewCard/TransactionToReviewCard.tsx, src/contexts/BankTransactionsContext/BankTransactionsContext.tsx, src/hooks/useProfitAndLoss/useProfitAndLossLTM.tsx, src/types/profit_and_loss.ts
[LAY-861](https://linear.app/layerfi/issue/LAY-861/use-pnl-summaries-data-in-transactions-to-review-and-in-onboarding)
=> feat: use pnl summaries data in transactions to review and in

src/styles/view.scss
=> fix: datepicker layout fix

src/components/LinkedAccountThumb/LinkedAccountThumb.tsx, src/styles/linked_accounts.scss
=> Fix linked account card heights

src/components/SyncingComponent/SyncingComponent.tsx, src/components/SyncingComponent/index.tsx, src/styles/loader.scss
=> feat: syncing component

src/components/BankTransactionsLoader/BankTransactionsLoader.tsx, src/components/BankTransactionsLoader/index.tsx, src/components/BankTransactionsTable/BankTransactionsTable.tsx, src/components/Button/SubmitButton.tsx, src/components/SkeletonTableLoader/SkeletonTableLoader.tsx, src/styles/bank_transactions.scss
https://github.com/user-attachments/assets/558e516e-c4e3-419b-a468-025e9a6dca04
=> feat: add skeleton loader in bank transactions with actions

src/components/ProfitAndLossSummaries/ProfitAndLossSummaries.tsx
Refetch data whenever date range in PnL context changes.
This is temporary fix.
=> fix: temporary fix to refetch summaries

package.json, src/components/ProfitAndLossDetailedCharts/DetailedChart.tsx, src/components/ProfitAndLossDetailedCharts/DetailedTable.tsx, src/components/ProfitAndLossDetailedCharts/ProfitAndLossDetailedCharts.tsx, src/components/ProfitAndLossSummaries/MiniChart.tsx, src/config/charts.ts, src/views/AccountingOverview/AccountingOverview.tsx
We specify these in code now (not css), so I've opted to allow prop-based overriding. Could change later.
=> allow spcifying chart color list

src/api/layer/bankTransactions.ts, src/components/BankTransactionList/BankTransactionList.tsx, src/components/BankTransactionList/BankTransactionListItem.tsx, src/components/BankTransactionMobileList/BankTransactionMobileList.tsx, src/components/BankTransactionMobileList/BankTransactionMobileListItem.tsx, src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/BankTransactions/BankTransactions.tsx, src/components/BankTransactionsTable/BankTransactionsTable.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/components/MatchForm/MatchForm.tsx, src/views/BankTransactionsWithLinkedAccounts/BankTransactionsWithLinkedAccounts.tsx
=> bookkeeping mode disables categorizations and updates

src/components/BankTransactions/BankTransactionsHeader.tsx
Accidentally removed that from the header
=> enable download button in bookkeeping view

.eslintrc.js, package-lock.json, package.json, src/components/DatePicker/DatePicker.tsx
This (again) broke Moxie's serverside imports.
=> remove explicit datepicker import

src/components/BankTransactionList/BankTransactionList.tsx, src/components/BankTransactionList/BankTransactionListItem.tsx, src/components/BankTransactionMobileList/BankTransactionMobileForms.tsx, src/components/BankTransactionMobileList/BankTransactionMobileList.tsx, src/components/BankTransactionMobileList/BankTransactionMobileListItem.tsx, src/components/BankTransactionMobileList/BusinessForm.tsx, src/components/BankTransactionMobileList/MatchForm.tsx, src/components/BankTransactionMobileList/PersonalForm.tsx, src/components/BankTransactionMobileList/SplitAndMatchForm.tsx, src/components/BankTransactionMobileList/SplitForm.tsx, src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/BankTransactions/BankTransactions.tsx, src/components/BankTransactionsTable/BankTransactionsTable.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/components/ProfitAndLossSummaries/ProfitAndLossSummaries.tsx, src/hooks/useBalanceSheet/useBalanceSheet.tsx, src/hooks/useBankTransactions/useBankTransactions.tsx, src/hooks/useChartOfAccounts/useChartOfAccounts.tsx, src/hooks/useDataSync/useDataSync.tsx, src/hooks/useJournal/useJournal.tsx, src/hooks/useLedgerAccounts/useLedgerAccounts.tsx, src/hooks/useLinkedAccounts/useLinkedAccounts.ts, src/hooks/useProfitAndLoss/useProfitAndLossLTM.tsx, src/hooks/useProfitAndLoss/useProfitAndLossQuery.tsx, src/hooks/useStatementOfCashFlow/useStatementOfCashFlow.tsx, src/hooks/useTasks/useTasks.tsx, src/types/layer_context.ts, src/types/profit_and_loss.ts, src/views/BankTransactionsWithLinkedAccounts/BankTransactionsWithLinkedAccounts.tsx
Fix not refreshing data on after "write" operation on any related resource.
Previous solution oversimplified identifying resources
https://github.com/user-attachments/assets/498e431d-ed6d-4f96-8b4b-ee97119637a7
=> fix: make sync data cache keys more granular

src/components/TasksHeader/TasksHeader.tsx, src/styles/panel.scss
=> book tasks -> bookkeeping tasks, GL header not sticky

src/components/BankTransactions/BankTransactions.tsx
while polling for transaction in initial syncing
=> drop to 1s

package.json, src/components/BankTransactions/BankTransactions.tsx, src/components/BankTransactions/utils.ts, src/hooks/useBankTransactions/useBankTransactions.tsx, src/hooks/useBankTransactions/utils.ts, src/index.tsx, src/types/bank_transactions.ts
also export Direction and make the categorizeViewProp
=> add all displayState

src/hooks/useBankTransactions/useBankTransactions.tsx, src/providers/LayerProvider/LayerProvider.tsx
For our purposes I think it is preferable for this to be called too often than not often enough. Thus I am just calling it every time we poll.
=> add onTransactionsFetched callback

src/components/BankTransactionMobileList/SplitForm.tsx, src/components/CategorySelect/CategorySelect.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/types/categories.ts
Splits are now properly retrieved on the front end. Tested on both mobile & web.
=> fix splits

src/hooks/useBankTransactions/useBankTransactions.tsx
=> remove both txns when confirming transfer

src/hooks/useProfitAndLossComparison/useProfitAndLossComparison.tsx
Ignore responses from old requests in P&L comparison
=> fix: ignore old api request in pnl comparison

src/components/ChartOfAccountsTable/ChartOfAccountsTable.tsx, src/components/JournalTable/JournalTable.tsx, src/components/JournalTable/JournalTableWithPanel.tsx, src/components/ProfitAndLossTable/ProfitAndLossTableComponent.tsx, src/styles/journal.scss
=> fix: check and add missing empty states

package.json, src/styles/typography.scss
https://layer-financial.slack.com/archives/C07HD95MQTT/p1725241251291749?thread_ts=1724830431.911479&cid=C07HD95MQTT
=> add no-wrap

src/components/BalanceSheet/BalanceSheet.tsx, src/components/BalanceSheetExpandAllButton/BalanceSheetExpandAllButton.tsx, src/components/BankTransactions/BankTransactionsHeader.tsx, src/components/Button/ExpandCollapseButton.tsx, src/components/ChartOfAccounts/ChartOfAccounts.tsx, src/components/ChartOfAccountsForm/ChartOfAccountsForm.tsx, src/components/ChartOfAccountsTable/ChartOfAccountsTableWithPanel.tsx, src/components/LedgerAccount/LedgerAccountIndex.tsx, src/components/LedgerAccountEntryDetails/LedgerAccountEntryDetails.tsx, src/styles/chart_of_accounts.scss, src/styles/ledger_account.scss, src/styles/table.scss
1. Unify "Download" and "Expand/Collapse" buttons
2. New headings in "Chart of Accounts" and "Ledger accounts"
=> feat: chart of accounts new headings

src/components/ActionableList/ActionableList.tsx, src/components/BankTransactionMobileList/BusinessCategories.tsx, src/components/BankTransactionMobileList/BusinessForm.tsx, src/components/CategorySelect/CategorySelectDrawer.tsx, src/styles/actionable_list.scss
New styling of the selection on the Bank Transactions mobile list.
=> feat: new styling of the selection on bank transactions mobile list

src/components/BalanceSheet/BalanceSheet.tsx, src/components/BalanceSheetTable/BalanceSheetTable.tsx, src/components/ChartOfAccountsTable/ChartOfAccountsTableWithPanel.tsx, src/components/Input/MultiSelect.tsx, src/components/JournalTable/JournalTableWithPanel.tsx, src/components/ProfitAndLossCompareOptions/ProfitAndLossCompareOptions.tsx, src/components/StatementOfCashFlow/StatementOfCashFlow.tsx, src/components/StatementOfCashFlowTable/StatementOfCashFlowTable.tsx, src/components/Typography/Heading.tsx, src/components/View/View.tsx, src/components/ViewHeader/ViewHeader.tsx, src/styles/profit_and_loss.scss, src/styles/table.scss, src/styles/typography.scss, src/styles/variables.scss, src/styles/view.scss, src/views/AccountingOverview/AccountingOverview.tsx, src/views/GeneralLedger/GeneralLedger.tsx, src/views/Reports/Reports.tsx
Unify and improve Reports headers.
=> feat: UI improvement of Reports headers

src/components/ProfitAndLoss/ProfitAndLoss.tsx, src/components/ProfitAndLossDownloadButton/ProfitAndLossDownloadButton.tsx, src/components/ProfitAndLossDownloadButton/index.tsx, src/components/ProfitAndLossReport/ProfitAndLossReport.tsx, src/components/ProfitAndLossReport/index.tsx, src/views/Reports/Reports.tsx
Copy of https://github.com/Layer-Fi/layer-react/pull/338 but with the new download button and separating both that and the report out
=> separate PnL download button and report

package.json, src/components/CategorySelect/CategorySelect.tsx, src/components/ChartOfAccountsForm/ChartOfAccountsForm.tsx, src/components/Pagination/Pagination.tsx, src/components/ProfitAndLossDetailedCharts/DetailedChart.tsx, src/hooks/useElementSize/useElementSize.ts, src/hooks/useElementViewSize/useElementViewSize.tsx, src/hooks/useJournal/useJournal.tsx
=> make compatible with react v17.0.2

src/components/Onboarding/Onboarding.tsx, src/views/AccountingOverview/AccountingOverview.tsx
=> override onboarding step in props

package.json, src/components/ActionableList/ActionableList.tsx, src/components/BankTransactionList/BankTransactionList.tsx, src/components/BankTransactionList/BankTransactionListItem.tsx, src/components/BankTransactionMobileList/BankTransactionMobileForms.tsx, src/components/BankTransactionMobileList/BankTransactionMobileList.tsx, src/components/BankTransactionMobileList/BankTransactionMobileListItem.tsx, src/components/BankTransactionMobileList/BusinessForm.tsx, src/components/BankTransactionMobileList/SplitAndMatchForm.tsx, src/components/BankTransactionMobileList/SplitForm.tsx, src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/BankTransactions/BankTransactions.tsx, src/components/BankTransactionsLoader/BankTransactionsLoader.tsx, src/components/BankTransactionsTable/BankTransactionsTable.tsx, src/components/CategorySelect/CategorySelect.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/views/BankTransactionsWithLinkedAccounts/BankTransactionsWithLinkedAccounts.tsx
I really don't like how much prop drilling I needed to do here. We should probably use Jotai at some point, or start moving some of these things into context
=> make tooltips toggleable

src/components/Button/Button.tsx, src/components/Button/DownloadButton.tsx, src/components/Button/SubmitButton.tsx, src/components/ChartOfAccountsTable/ChartOfAccountsTable.tsx, src/styles/button.scss
Add `tooltip` to `<Button />`.
https://github.com/user-attachments/assets/bdc6ecee-66c9-49a4-b407-567bf9fbd259
=> feat: tooltip to button

package.json, src/api/layer.ts, src/api/layer/profit_and_loss.ts, src/components/ProfitAndLossDownloadButton/ProfitAndLossDownloadButton.tsx, src/components/ProfitAndLossReport/ProfitAndLossReport.tsx, src/contexts/ProfitAndLossComparisonContext/ProfitAndLossComparisonContext.tsx, src/hooks/useProfitAndLossComparison/useProfitAndLossComparison.tsx
[comparisonProfitAndLoss.csv](https://github.com/user-attachments/files/17141648/comparisonProfitAndLoss.csv)
Example csv above ^
=> Use comparison P&L csv for download button

package-lock.json, src/api/layer.ts, src/api/layer/bankTransactions.ts, src/api/layer/tasks.ts, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/components/Input/FileInput.tsx, src/components/TasksListItem/TasksListItem.tsx, src/contexts/TasksContext/TasksContext.tsx, src/hooks/useTasks/mockData.ts, src/hooks/useTasks/useTasks.tsx, src/providers/LayerProvider/LayerProvider.tsx, src/types/bank_transactions.ts, src/types/file_upload.ts, src/types/tasks.ts
Add task type where the user must upload a specified document
=> Business task file uploads

src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/styles/file_thumb.scss
Fix positioning of the tooltip over receipt thumb.
Remove unused `fetchMetadata` function.
=> fix: receipt tooltip

src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/BankTransactions/BankTransactions.tsx, src/components/BankTransactionsLoader/BankTransactionsLoader.tsx, src/components/BankTransactionsTable/BankTransactionsTable.tsx, src/components/Button/IconButton.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/components/FileThumb/FileThumb.tsx, src/components/FileThumb/index.tsx, src/components/Input/FileInput.tsx, src/icons/Eye.tsx, src/icons/File.tsx, src/styles/bank_transactions.scss, src/styles/file_thumb.scss, src/styles/index.scss
Add new UI for receipt upload in Bank Transactions
=> feat: receipt upload ui

src/components/ProfitAndLossDownloadButton/ProfitAndLossDownloadButton.tsx
For consistency with the P&L chart
=> use daterange in pnl csv download

package.json, src/components/ProfitAndLoss/ProfitAndLoss.tsx, src/components/ProfitAndLossDownloadButton/ProfitAndLossDownloadButton.tsx, src/hooks/useProfitAndLoss/useProfitAndLoss.tsx, src/styles/profit_and_loss_detailed_charts.scss, src/views/ProjectProfitability/ProjectProfitability.tsx
Remove header for overview, make transactions categorized only, adjust z axis for project dropdown, make download button use tag filters
=> project tweaks

src/styles/bank_transactions.scss
soft revert of https://github.com/Layer-Fi/layer-react/pull/221
=> fix bank transactions header z index

src/api/layer.ts, src/api/layer/journal.ts, src/components/JournalEntryDetails/JournalEntryDetails.tsx, src/contexts/JournalContext/JournalContext.tsx, src/hooks/useJournal/useJournal.tsx, src/styles/journal.scss, src/styles/tooltip.scss
Reverse Journal entry
[LAY-1030](https://linear.app/layerfi/issue/LAY-1030/add-reversal-capability)
=> feat: add reversing journal entries

src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/ModeSelector/DatePickerModeSelector.tsx, src/components/DatePicker/ModeSelector/date-picker-mode-selector.scss, src/components/ProfitAndLossDatePicker/ProfitAndLossDatePicker.tsx, src/components/StatementOfCashFlow/StatementOfCashFlow.tsx, src/styles/datepicker.scss
These changes help standardize filtering in a date component.
=> feat(date-picker): switch between selection modes

src/components/LinkedAccounts/LinkedAccountItemThumb.tsx, src/components/LinkedAccounts/LinkedAccountsContent.tsx, src/components/LinkedAccounts/index.tsx, src/components/PlatformOnboarding/LinkAccounts.tsx, src/components/PlatformOnboarding/index.tsx, src/index.tsx, src/styles/index.scss, src/styles/link_accounts.scss, src/views/AccountingOverview/AccountingOverview.tsx
Add `<LinkAccounts />` component.
Basic usage:
```tsx
<LinkAccounts />
```
<br/>
<br/>
With optional props: wrapped in box, optional title, footer buttons with custom texts:
```tsx
<LinkAccounts
title='Let’s connect the bank accounts and credit cards you use for your business.'
inBox
onBack={() => console.log('back')}
onNext={() => console.log('next')}
/>
```
=> feat: link accounts component

src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/DatePickerOptions.tsx, src/components/DatePicker/ModeSelector/DatePickerModeSelector.tsx, src/components/ProfitAndLossDatePicker/ProfitAndLossDatePicker.tsx, src/components/ProfitAndLossReport/ProfitAndLossReport.tsx, src/components/StatementOfCashFlow/StatementOfCashFlow.tsx, src/views/ProjectProfitability/ProjectProfitability.tsx, src/views/Reports/Reports.tsx
Adding in an option (specifiable at any level of component) for custom date ranges.
=> allow custom date range props from top level

src/api/layer/chart_of_accounts.ts, src/components/ChartOfAccounts/ChartOfAccounts.tsx, src/hooks/useLedgerAccounts/useLedgerAccounts.tsx, src/views/GeneralLedger/GeneralLedger.tsx
=> add show/hide reversals to gl settings

src/components/DatePicker/DatePickerOptions.tsx, src/components/DatePicker/ModeSelector/DatePickerModeSelector.tsx, src/components/ProfitAndLoss/ProfitAndLoss.tsx, src/components/ProfitAndLossDatePicker/ProfitAndLossDatePicker.tsx, src/components/ProfitAndLossReport/ProfitAndLossReport.tsx, src/components/StatementOfCashFlow/StatementOfCashFlow.tsx, src/views/Reports/Reports.tsx, src/views/Reports/reportTypes.ts
This feature change is intended for MoeGo; they want to be able to show custom date ranges.
=> fix(date-picker): limit defaults

src/components/Button/Button.tsx, src/components/JournalEntryDetails/JournalEntryDetails.tsx, src/styles/journal.scss
=> prevent reversing same entry more than once

src/styles/panel.scss
This one was fun to track down. The date picker in the manual journal entry form was being blocked by the sidebar panel.
=> fix panel z idx

src/components/ProfitAndLossDetailedCharts/DetailedChart.tsx, src/components/ProfitAndLossDetailedCharts/DetailedTable.tsx, src/components/ProfitAndLossSummaries/MiniChart.tsx, src/components/ProfitAndLossSummaries/ProfitAndLossSummaries.tsx, src/views/AccountingOverview/AccountingOverview.tsx
This change is intended to make our chart customization more consistent.
=> feat(charts): control mini chart colors

bin/build.js, bin/removeDeps.js, package-lock.json, package.json, src/components/DatePicker/DatePicker.tsx
I have been extensively testing this locally... but I would appreciate at least one other person trying it on their machine. I would advise deleting the `/dist` directory so that there is an obvious clean slate.
=> refactor!: add a dev-mode into the build flow

src/api/layer/bankTransactions.ts, src/api/layer/tasks.ts, src/components/BankTransactionMobileList/useMemoText.tsx, src/components/BankTransactions/BankTransactionsHeader.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/components/ProfitAndLossDownloadButton/ProfitAndLossDownloadButton.tsx, src/contexts/LayerContext/LayerContext.tsx, src/hooks/useAuth.ts, src/hooks/useBalanceSheet/useBalanceSheet.tsx, src/hooks/useBankTransactions/useBankTransactions.tsx, src/hooks/useChartOfAccounts/useChartOfAccounts.tsx, src/hooks/useJournal/useJournal.tsx, src/hooks/useLedgerAccounts/useLedgerAccounts.tsx, src/hooks/useLinkedAccounts/useLinkedAccounts.ts, src/hooks/useProfitAndLoss/useProfitAndLossLTM.tsx, src/hooks/useProfitAndLoss/useProfitAndLossQuery.tsx, src/hooks/useProfitAndLossComparison/useProfitAndLossComparison.tsx, src/hooks/useQuickbooks/useQuickbooks.ts, src/hooks/useReceipts/useReceipts.ts, src/hooks/useStatementOfCashFlow/useStatementOfCashFlow.tsx, src/hooks/useTasks/useTasks.tsx, src/providers/AuthInputProvider.tsx, src/providers/BusinessProvider/BusinessProvider.tsx, src/providers/LayerProvider/LayerProvider.tsx, src/types/layer_context.ts
This is a temporary measure - looks worse in the short term, but gets rid of bad use effects. I'm going to be stacking PRs to help our data-loading get into better shape.
=> refactor: pull-out auth input into own context

src/hooks/useLinkedAccounts/useLinkedAccounts.ts
There was never a need to poll, since part of the `/exchange` endpoint does synchronously gather new accounts (but not transactions).
This change will ensure that if there are no accounts to warn about, then the modal will just fade away.
=> fix: no need to poll - just preload the modal if appropriate

src/api/layer.ts, src/api/layer/tasks.ts, src/components/BankTransactionMobileList/BusinessForm.tsx, src/components/BankTransactionMobileList/MatchForm.tsx, src/components/BankTransactionMobileList/PersonalForm.tsx, src/components/BankTransactionMobileList/SplitForm.tsx, src/components/BankTransactionReceipts/BankTransactionReceipts.tsx, src/components/Input/FileInput.tsx, src/components/Tasks/Tasks.tsx, src/components/TasksListItem/TasksListItem.tsx, src/contexts/TasksContext/TasksContext.tsx, src/hooks/useTasks/mockData.ts, src/hooks/useTasks/useTasks.tsx, src/styles/button.scss, src/styles/tasks.scss, src/types/tasks.ts
1. Enable user to select multiple files for doc upload
2. Fix css issue where collapsed task rows were covering the task rows below
3. Display uploaded document links in completed task
4. Enable user to delete the uploads to a task, moving the task back to the TODO state
5. Enable user to add/edit description on a document upload task
=> Misc doc upload task updates

src/api/layer/tasks.ts, src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/ModeSelector/DatePickerModeSelector.tsx, src/components/Tasks/Tasks.tsx, src/components/TasksHeader/TasksHeader.tsx, src/components/TasksList/TasksList.tsx, src/components/TasksListItem/TasksListItem.tsx, src/components/TasksMonthSelector/TaskMonthTile.tsx, src/components/TasksMonthSelector/TasksMonthSelector.tsx, src/components/TasksMonthSelector/tasksMonthSelector.scss, src/components/TasksMonthSelector/types.ts, src/components/TasksPending/TasksPending.tsx, src/contexts/TasksContext/TasksContext.tsx, src/hooks/useTasks/mockData.ts, src/hooks/useTasks/useTasks.tsx, src/styles/datepicker.scss, src/styles/index.scss, src/styles/tasks.scss, src/types/tasks.ts
Add monthly view to the Bookkeeping tasks.
https://github.com/user-attachments/assets/42f78509-f2ed-4e7a-9119-cc9ca29a1ff3
=> feat: bookkeeping tasks - monthly view

package-lock.json, package.json
We are ready to move to the next version of the components.
=> build: version 0.1.82

package-lock.json, package.json
We want to release another series of quick-fixes.
=> build: version 0.1.83

package-lock.json, package.json
I'd like to have this merged right before we tag a release.
=> build: v0.1.84-alpha

package-lock.json, package.json
The `postinstall` script was a bad idea - also runs when the package is consumed.
=> build: v0.1.84-alpha.1

package-lock.json, package.json
The testing of the alpha release concluded without any major issues.
=> build: v0.1.84

package-lock.json, package.json
This commit will be tagged as the alpha release.
=> v0.1.86-alpha

package-lock.json, package.json
I am cutting a new alpha release for internal testing.
=> 0.1.88-alpha

package-lock.json, package.json, src/components/BankTransactionMobileList/BankTransactionMobileListItem.tsx, src/components/BankTransactionMobileList/SplitForm.tsx, src/components/BankTransactionMobileList/utils.ts, src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/BankTransactionRow/SplitTooltipDetails.tsx, src/components/CategorySelect/CategorySelect.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/components/JournalForm/JournalFormEntryLines.tsx, src/hooks/useJournal/useJournal.tsx, src/providers/GlobalDateStore/GlobalDateStoreProvider.tsx, src/types/bank_transactions.ts, src/types/categories.ts, src/utils/journal.ts
**Linear**: LAY-1154 and LAY-1158
- Unified date range will not allow end dates beyond today
- Explicitly set a default date in the journal form
- Fixes issue where accounts without an ID - only a `STABLE_NAME` - are not handled properly in the dropdown.
=> fix: alpha release fixes

src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx
I am unsure how this was not an already-existing issue.
=> fix: unchecked access when getting default category

package-lock.json, package.json
We need another alpha release to incorporate bug fixes.
=> 0.1.88-alpha.2

src/types/bills.ts, src/types/tags.ts, src/types/vendors.ts, src/utils/bills.ts, src/utils/format.ts, src/utils/vendors.ts
This PR brings smaller changes from a large Bills PR.
- Bills and Vendors types
- Bills and Vendors helper functions (utils)
=> feat: bills and vendors types and utils

src/components/BankTransactions/BankTransactions.tsx, src/components/JournalTable/JournalTableWithPanel.tsx, src/components/LedgerAccount/LedgerAccountIndex.tsx, src/components/Pagination/Pagination.tsx, src/components/TasksList/TasksList.tsx, src/styles/bank_transactions.scss, src/styles/journal.scss, src/styles/ledger_account.scss, src/styles/pagination.scss, src/styles/tasks.scss
Refactoring Pagination component.
Pagination was wrapped into additional containers with the same styling in many components (ie. BankTransactions, Journal, etc.). This PR moves that container into `<Pagination />` component.
This change is also implemented in the Bills PR, but that change touches many files and most changes were produced by linters. So to keep Bills PR small as possible and easier to review, I'm moving this refactor to this PR.
- wrap Pagination into the container giving proper spacing and positioning across the application
- remove styles and refactor related components
=> refactor: pagination

src/hooks/useProfitAndLossComparison/useProfitAndLossComparison.tsx, src/hooks/useProfitAndLossComparison/utils.ts
This is going to be merged into a base PR by @tomaszantas.
=> fix: comparison P&L should support custom date ranges

package-lock.json, package.json
I am going to cut another alpha release after merging this.
=> 0.1.88-alpha.3

src/utils/request/toDefinedSearchParameters.ts
Our function that builds query parameters needs to anticipate transforming arrays into `value=1&value=2`.
=> feat: `toDefinedSearchParameters` should handle lists

src/api/layer.ts, src/api/layer/bills.ts, src/api/layer/vendors.ts, src/contexts/VendorsContext.tsx, src/hooks/useVendors.ts, src/types/bills.ts
Selected changes from the Bills PR #357 are moved here to make the original PR easier to review.
- add API functions for Bills and Vendors
- add VendorSelect component
- update Bills types
=> feat: bills and vendors api, vendor select

package-lock.json, package.json
=> bump alpha version

eslint.config.mjs, src/components/BankTransactionList/BankTransactionList.tsx, src/components/BankTransactionList/BankTransactionListItem.tsx, src/components/BankTransactionMobileList/BankTransactionMobileList.tsx, src/components/BankTransactionMobileList/BankTransactionMobileListItem.tsx, src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/BankTransactions/BankTransactions.tsx, src/components/BankTransactionsTable/BankTransactionsTable.tsx, src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx, src/hooks/bookkeeping/useBookkeepingStatus.ts, src/providers/LegacyModeProvider/LegacyModeProvider.tsx, src/utils/bookkeeping/isCategorizationEnabled.ts, src/views/BankTransactionsWithLinkedAccounts/BankTransactionsWithLinkedAccounts.tsx
The ability to categorize transactions can be driven from the server.
=> feat: deprecate bookkeeping `mode`

package-lock.json, package.json
I would like to include changes that propagate bookkeeping configuration deep into the components.
=> v0.1.88-alpha.5

package-lock.json, package.json
=> update package version to 0.1.88

src/api/layer/businessPersonnel/updateBusinessPersonnel.ts, src/hooks/businessPersonnel/types.ts, src/hooks/businessPersonnel/useBusinessPersonnel.ts, src/hooks/businessPersonnel/useCreateBusinessPersonnel.ts, src/hooks/businessPersonnel/useUpdateBusinessPersonnel.ts, src/types/utility/branded.ts, src/utils/array/isStringArray.ts, src/utils/array/readonlyTransformations.ts, src/utils/request/toDefinedSearchParameters.ts, src/utils/swr/withSWRKeyTags.ts
We want to be able to collect information about individuals working for (or supporting) the business during onboarding. This is how we'll collect a email address + phone number for a specific person.
If these hook are insufficient (e.g. we need multi-updates), then I can make those special hooks too.
=> feat: introduce hooks for working with Business Personnel

src/components/ProfitAndLossDetailedCharts/DetailedChart.tsx
There was a (minor) typescript build issue in #523.
=> fix: TS build error

src/components/ProgressSteps/ProgressSteps.tsx, src/components/ProgressSteps/progressSteps.scss, src/styles/index.scss
Add `<ProgressSteps />` component - it's a part of the Onboarding.
- add `<ProgressSteps />` component
https://github.com/user-attachments/assets/70f1c7df-17cd-41f8-a652-7d0c198b4371
=> feat: progress steps component

package-lock.json, package.json
We want to get out an alpha release for internal testing.
=> v0.1.89-alpha

src/api/layer/tasks.ts, src/components/DatePicker/DatePicker.tsx, src/components/Tasks/Tasks.tsx, src/components/TasksHeader/TasksHeader.tsx, src/styles/datepicker.scss
Follow up to: #520 
Highlight years in Tasks DatePicker if year contains unresolved task.
- DatePicker - highlight years and navigation arrows if `highlightYears` is set
- Tasks - highlight years if any unresolved task
=> feat: add badges to date picker

src/components/LinkedAccounts/ConfirmationModal/LinkedAccountsConfirmationModal.tsx
I broke the types on the main branch in #532.
=> fix: build issue related to types

src/hooks/bookkeeping/periods/useBookkeepingPeriods.ts
We made an API-level change to adjust the statuses of bookkeeping periods.
=> fix(types): adjust bookkeeping period statuses

package-lock.json, package.json
This is a prerequisite to cutting an alpha release for further internal testing.
=> v0.1.91-alpha

src/components/ProfitAndLossSummaries/ProfitAndLossSummaries.tsx, src/components/ui/Button/Button.tsx, src/components/ui/Button/button.scss
I want a button to contain a spinner _and_ have zero layout shift when changing states.
=> fix: adding spinner inside button

src/components/BankTransactionList/BankTransactionListItem.tsx, src/components/BankTransactionMobileList/BankTransactionMobileListItem.tsx, src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/BankTransactions/BankTransactions.tsx, src/components/Onboarding/ConnectAccount.tsx, src/contexts/BankTransactionsContext/BankTransactionsContext.tsx, src/hooks/useBankTransactions/index.tsx, src/hooks/useBankTransactions/types.ts, src/hooks/useBankTransactions/useAugmentedBankTransactions.tsx, src/providers/BankTransactionsProvider/BankTransactionsProvider.tsx
I plan on making some changes to `useBankTransactions` to help me support search strings. I want to break this into smaller PRs that can be more easily reviewed.
=> fix: preparatory clean-up for working with bank transactions

package-lock.json, package.json, src/api/layer/bankTransactions.ts, src/hooks/useBankTransactions/useBankTransactions.ts
This change is mostly intended to cut an alpha release.
I have coupled the version bump with a placeholder for the `descriptionFilter` query parameter.
=> feat: add `descriptionFilter` to `useBankTransactions`

src/components/BookkeepingStatus/BookkeepingStatusPanelNotification.tsx, src/components/BookkeepingStatus/utils.tsx, src/components/Tasks/TaskStatusBadge.tsx
This is just a placeholder PR to cleanly merge into the upstream branch.
=> fix: add comments around a container query

src/hooks/bookkeeping/periods/useBookkeepingYearsStatus.ts, src/utils/bookkeeping/periods/getFilteredBookkeepingPeriods.ts
If a business did not purchase bookkeeping in 2023, then we should not see any "2023" tab for them.
=> fix: hide years without any active bookkeeping period

package-lock.json, package.json, src/components/BookkeepingStatus/BookkeepingStatus.tsx, src/components/BookkeepingStatus/bookkeepingStatus.scss, src/components/BookkeepingStatus/utils.tsx, src/components/Tasks/TaskStatusBadge.tsx, src/components/Tasks/TasksPending.tsx
Changes:
- Removes our usage of red (icons).  User-actions are prompted from yellow
- Remove non-standard dark yellow box.
=> fix: standardize bookkeeping notification colors

src/components/Tasks/Tasks.tsx, src/components/Tasks/TasksPanelNotification.tsx, src/components/Tasks/tasks.scss, src/hooks/bookkeeping/useBankAccounts.ts, src/types/linked_accounts.ts, src/views/BookkeepingOverview/BookkeepingOverview.tsx
Change the tasks banner to show a separate banner if there are any disconnected accounts
=> Notification for accounts being disconnected

package-lock.json, package.json
This is needed before internal testing.
=> v0.1.94-alpha

src/components/domain/transactions/actions/transactionsActions.scss
The search box is takes-up a lot of horizontal space on a wide screen.
=> [LAY-1283] fix: make transaction search box smaller (relatively)

package-lock.json, package.json
This is a prerequisite to cutting an alpha release.
=> v0.1.95-alpha

package-lock.json, package.json, src/components/BankTransactions/BankTransactionsTableEmptyState.tsx
I was missing a `return` statement for a certain state 🙃
=> fix: properly `return` the empty state

src/components/BankTransactionReceipts/BankTransactionReceipts.tsx, src/contexts/ReceiptsContext/ReceiptsContext.ts, src/hooks/useQuickbooks/useQuickbooks.ts, src/hooks/useReceipts/index.ts, src/hooks/useReceipts/useReceipts.ts, src/providers/ReceiptsProvider/ReceiptsProvider.tsx, src/views/AccountingOverview/AccountingOverview.tsx, src/views/ProjectProfitability/ProjectProfitability.tsx
=> chore: lint fixes

src/components/BankTransactionMobileList/utils.ts, src/components/BankTransactionRow/BankTransactionRow.tsx, src/components/BankTransactionRow/SplitTooltipDetails.tsx, src/components/CategorySelect/CategorySelect.tsx, src/components/CategorySelect/CategorySelectDrawer.tsx, src/components/CategorySelect/categorySelect.scss, src/components/CategorySelect/components/CategoriesList.tsx, src/components/CategorySelect/components/ComboBoxInput.tsx, src/components/CategorySelect/components/ListItem.tsx, src/components/CategorySelect/components/ListSection.tsx, src/components/CategorySelect/components/MatchesList.tsx, src/components/CategorySelect/components/MenuSection.tsx, src/components/CategorySelect/components/SuggestionsList.tsx, src/components/CategorySelect/types.ts, src/components/CategorySelect/utils.ts, src/components/Input/Input.tsx, src/components/Tooltip/Tooltip.tsx, src/styles/inputs.scss
Use ComboBox in CategorySelect
=> feat: category select as combobox

src/components/LinkedAccounts/ConfirmationModal/LinkedAccountsConfirmationModal.tsx, src/components/ui/Button/button.scss, src/components/ui/Modal/ModalSlots.tsx, src/components/ui/Modal/modalSlots.scss, stylelint.config.mjs
The button in the modal was defaulting to a size of medium - not icon-specific sizing - so it was overflowing its boundaries.
=> [LAY-1330] fix: button overflow from confirmation modal

package-lock.json, package.json
This is a prerequisite to getting the next alpha release of the components live.
=> v0.1.98-alpha

package-lock.json, package.json
We need to cut another alpha release.
=> v0.1.99-alpha

src/components/Integrations/Integrations.tsx, src/index.tsx
This is a prerequisite to creating a `next` branch.
=> fix: mark `Integrations` as unstable

package-lock.json, package.json, src/styles/inputs.scss, stylelint.config.mjs
This is a very simple fix... but I've decided to make some tweaks to our `stylelint.config.mjs` to help us in the future.
=> fix: a `textarea` should have an explicit background-color

package-lock.json, package.json
This is a "mile-marker" for a set of reasonable changes.
=> v0.1.99-alpha.3

package-lock.json, package.json, src/api/layer.ts, src/api/layer/bankTransactions.ts, src/api/layer/linked_accounts.ts, src/hooks/bookkeeping/periods/tasks/useDeleteUploadsOnTask.ts, src/hooks/bookkeeping/periods/tasks/useSubmitResponseForTask.ts, src/hooks/bookkeeping/periods/tasks/useUpdateTaskUploadDescription.ts, src/hooks/bookkeeping/periods/tasks/useUploadDocumentsForTask.ts, src/hooks/bookkeeping/useBankAccounts.ts, src/hooks/business/useUpdateBusiness.ts, src/hooks/businessPersonnel/useCreateBusinessPersonnel.ts, src/hooks/businessPersonnel/useUpdateBusinessPersonnel.ts, src/hooks/useBankTransactions/useAugmentedBankTransactions.tsx, src/hooks/useBankTransactions/useBankTransactions.ts, src/hooks/useBankTransactions/useCategorizeBankTransaction.ts, src/hooks/useBankTransactions/useMatchBankTransaction.ts, src/hooks/useBankTransactions/useUpdateBankTransactionMetadata.ts, src/hooks/useChartOfAccounts/useCreateChildAccount.tsx, src/hooks/useLinkedAccounts/useLinkedAccounts.ts, src/hooks/useLinkedAccounts/useListExternalAccounts.ts, src/styles/button.scss, src/styles/inputs.scss, src/styles/profit_and_loss_detailed_charts.scss, stylelint.config.mjs
This is the release branch for version `v0.1.99`. All work needs to point to this branch.
=> [Release] v0.1.99

package-lock.json, package.json, src/components/Integrations/Integrations.tsx, src/components/Integrations/IntegrationsQuickbooksItemThumb/IntegrationsQuickbooksItemThumb.tsx, src/components/Integrations/IntegrationsQuickbooksItemThumb/IntegrationsQuickbooksItemThumbFooter.tsx, src/components/Integrations/IntegrationsQuickbooksItemThumb/IntegrationsQuickbooksUnlinkConfirmationModal.tsx, src/index.tsx
This is the release branch for version v0.1.100. All work needs to point to this branch.
=> [Release] v0.1.100

src/components/LinkedAccounts/BasicLinkedAccount/basicLinkedAccount.scss, src/components/PlatformOnboarding/Container/linkAccountsListContainer.scss, src/components/ui/Modal/modalSlots.scss, src/components/ui/SearchField/minimalSearchField.scss, src/styles/period_picker.scss, src/styles/profit_and_loss.scss
**Linear**: [LAY-1390](https://linear.app/layerfi/issue/LAY-1390/kesin-clear-in-search-box-is-overflowing)
The "clear-button" is getting crowded out.
=> [LAY-1390] fix: prefer `minmax(0, 1fr)`

README.md
Remove the old onboarding component from the README
=> rm onboarding from readme

package-lock.json, package.json, src/components/Button/SubmitButton.tsx, src/components/CsvUpload/CopyTemplateHeadersButtonGroup.tsx, src/components/CsvUpload/CsvUpload.tsx, src/components/CsvUpload/DownloadCsvTemplateButton.tsx, src/components/CsvUpload/ValidateCsvTable.tsx, src/components/CsvUpload/csvUpload.scss, src/components/CsvUpload/types.ts, src/components/CustomAccountForm/CustomAccountForm.tsx, src/components/UploadTransactions/UploadTransactions.tsx, src/components/UploadTransactions/UploadTransactionsUploadCsvStep.tsx, src/components/UploadTransactions/UploadTransactionsValidateCsvStep.tsx, src/components/UploadTransactions/template.ts, src/components/UploadTransactions/uploadTransactions.scss, src/hooks/customAccounts/types.ts, src/hooks/customAccounts/useCreateCustomAccount.ts, src/hooks/customAccounts/useCreateCustomAccountTransactions.ts, src/hooks/customAccounts/useCustomAccountParseCsv.ts, src/hooks/customAccounts/useCustomAccounts.ts
=> feat: Upload transactions by CSV (cont'd)

src/components/CsvUpload/CsvUpload.tsx, src/styles/index.scss
We had a bad merge and lost the CSV and transactions upload CSS files. Also refactors out some constant values.
=> fix: refactor out consts and fix CSS files

eslint.config.mjs, src/components/BankTransactionMobileList/MatchForm.tsx, src/components/Bills/BillsList.tsx, src/hooks/visibility/useDelayedVisibility.ts
I found a few uses of `useEffect` that were easier to kill.
=> fix: try to kill a couple `useEffect` calls

package-lock.json, package.json
We are cutting another release for internal testing.
=> v0.1.102-alpha.3

package-lock.json, package.json
This is a quick fix to resolve a bad merge.
=> v0.1.102-alpha.4

src/utils/swr/defaultSWRConfig.ts
This change is intended to help catch the long-tail of cases where the UI has gone stale (while some server-side state has drifted).
=> fix: add refresh interval at 10 minutes

src/features/tags/api/useCreateTagDimension.ts, src/features/tags/api/useCreateTagValueDefinition.ts, src/features/tags/api/useTagDimensions.ts, src/features/tags/tagSchemas.ts
This is valuable for future work with creating tag dimensions (or just creating a value definition on that dimension).
=> feat: add hooks for creating tag dimensions

src/api/layer.ts, src/api/layer/journal.ts, src/components/JournalTable/JournalTableWithPanel.tsx, src/features/ledger/entries/[ledgerEntryId]/tags/api/useRemoveTagFromLedgerEntry.ts, src/features/ledger/entries/[ledgerEntryId]/tags/api/useTagLedgerEntry.ts, src/features/ledger/entries/api/useListLedgerEntries.ts, src/hooks/useJournal/useJournal.tsx, src/types/journal.ts, src/types/ledger_accounts.ts
These changes are intended to set-up future UI work where ledger entries can be tagged.
=> feat: add hooks for interacting with tags on the ledger

package-lock.json, package.json
We need to cut another internal `alpha` release for testing purposes.
=> v0.1.102-alpha.5

src/features/tags/components/TagSelector.tsx, src/features/tags/components/tagSelector.scss
=> fix: indention on tag selector dropdown and tag selection styles

src/components/BankTransactions/BankTransactions.tsx, src/features/customers/api/useListCustomers.ts, src/features/vendors/api/useListVendors.ts
=> fix: preload customer/vendor data

src/styles/bank_transactions.scss, src/styles/table.scss
When there is a "Match" badge within the categorization combobox, it crowds-out the meaningful info. The short-term solution is to change the ratios of the table.
=> fix: increase (relative) width of categorization input

package-lock.json, package.json
We need this to cut another release.
=> v0.1.103-alpha

src/components/LedgerAccount/LedgerAccountIndex.tsx, src/components/LedgerAccount/LedgerAccountRow.tsx, src/contexts/LedgerAccountsContext/LedgerAccountsContext.tsx, src/features/ledger/accounts/[ledgerAccountId]/api/useListLedgerAccountLines.ts, src/hooks/useLedgerAccounts/useLedgerAccounts.tsx
Paginate ledger account line items, similar to how we paginate ledger entries
https://github.com/user-attachments/assets/eda56fff-816e-425a-98db-594012e7ed31
=> Paginate ledger account lines

src/components/LinkedAccounts/LinkedAccounts.tsx, src/components/LinkedAccounts/LinkedAccountsContent.tsx, src/views/BankTransactionsWithLinkedAccounts/BankTransactionsWithLinkedAccounts.tsx
=> props for hiding add accounts

src/styles/actionable_row.scss
=> @container change for vertical stacking

src/components/Invoices/Invoices.tsx, src/index.tsx
Add `unstable_Invoices` to the index file to make it available in `@layerfi/components` for demos.
=> feat: expose unstable invoices for demos

package-lock.json, package.json
=> v0.1.106-alpha

src/components/Invoices/InvoiceForm/InvoiceForm.tsx, src/components/Invoices/InvoiceForm/invoiceForm.scss, src/components/Invoices/InvoiceForm/useInvoiceForm.ts, src/components/ui/Checkbox/Checkbox.tsx, src/components/ui/Checkbox/checkbox.scss, src/features/features.scss, src/features/forms/components/BaseFormTextField.tsx, src/features/forms/components/FormBigDecimalField.tsx, src/features/forms/components/FormCheckboxField.tsx, src/features/forms/components/FormCurrencyField.tsx, src/features/forms/components/FormTextAreaField.tsx, src/features/forms/components/FormTextField.tsx, src/features/forms/forms.scss, src/features/forms/hooks/useForm.tsx, src/styles/internal_variables.scss
This PR creates a new `FormCheckboxField` and uses it in the invoices form.
=> feat: create new checkbox field and use in invoices form

src/components/Invoices/InvoiceDetail/InvoiceDetail.tsx, src/components/Invoices/InvoiceForm/InvoiceForm.tsx, src/components/Invoices/InvoiceForm/invoiceForm.scss, src/components/Invoices/InvoiceTermsComboBox/InvoiceTermsComboBox.tsx, src/components/ui/Checkbox/checkbox.scss, src/components/ui/ComboBox/ComboBox.tsx, src/components/ui/ComboBox/comboBox.scss, src/components/ui/Date/Date.scss, src/components/ui/Date/Date.tsx, src/components/ui/Form/form.scss, src/features/customers/components/CustomerSelector.tsx, src/features/forms/components/BaseFormTextField.tsx, src/features/forms/components/FormBigDecimalField.tsx, src/features/forms/components/FormCheckboxField.tsx, src/features/forms/components/FormDateField.tsx, src/features/forms/components/FormTextAreaField.tsx, src/features/forms/components/FormTextField.tsx, src/features/forms/types.ts
This PR creates a view-only version of the invoice form for already-created invoices. This allows end users to view their invoice without accidentally editing it unless they click the "Edit Invoice" button.
=> feat: create view-only variant of invoice form

src/components/UploadTransactions/UploadTransactionsValidateCsvStep.tsx
=> fix invalid import

package-lock.json, package.json
Bump package version for v0.1.107-alpha release.
=> v0.1.107-alpha

src/api/layer/authenticated_http.ts, src/components/BaseConfirmationModal/BaseConfirmationModal.tsx, src/components/ChartOfAccountsTable/ChartOfAccountsTable.tsx, src/contexts/ChartOfAccountsContext/ChartOfAccountsContext.tsx, src/features/ledger/accounts/[ledgerAccountId]/api/useDeleteLedgerAccount.ts, src/hooks/useChartOfAccounts/useChartOfAccounts.tsx, src/styles/chart_of_accounts.scss, src/types/chart_of_accounts.ts
Adds a ledger account deletion button to the Chart of Accounts view
Deletion button shows on accounts that can be deleted. When you click the delete button, a modal pops up confirming if you want to delete the account. If confirmed, the selected account will be deleted and no longer seen in the chart of accounts.
=> Added ledger account delete button

src/components/ChartOfAccountsTable/ChartOfAccountsTable.tsx
Added tooltip message about sub accounts for account deletion
Added tooltip message to detail that you can not delete accounts with sub accounts
=> Added tooltip message about sub accounts for account deletion

src/components/BaseConfirmationModal/BaseConfirmationModal.tsx, src/components/BaseDetailView/BaseDetailView.tsx, src/components/Invoices/InvoiceDetail/InvoiceDetail.tsx, src/components/Invoices/InvoiceForm/InvoiceForm.tsx, src/components/Invoices/InvoiceForm/formUtils.ts, src/components/Invoices/InvoiceForm/useInvoiceForm.ts, src/components/Invoices/InvoicePaymentForm/InvoicePaymentForm.tsx, src/components/Invoices/InvoicePaymentForm/formUtils.ts, src/components/Invoices/InvoicePaymentForm/invoicePaymentForm.scss, src/components/Invoices/InvoicePaymentForm/useInvoicePaymentForm.ts, src/components/Invoices/InvoiceSummaryStats/InvoiceSummaryStats.tsx, src/components/LinkedAccounts/ConfirmationModal/LinkedAccountsConfirmationModal.tsx, src/components/LinkedAccounts/OpeningBalanceModal/OpeningBalanceModal.tsx, src/components/PaymentMethod/PaymentMethodComboBox.tsx, src/components/PaymentMethod/paymentMethodComboBox.scss, src/components/PaymentMethod/schemas.ts, src/components/ui/ComboBox/ComboBox.tsx, src/components/ui/Input/textArea.scss, src/components/ui/Modal/Modal.tsx, src/components/ui/Modal/modal.scss, src/components/ui/Modal/modalSlots.scss, src/features/forms/components/FormBigDecimalField.tsx, src/features/invoices/api/useListInvoices.tsx, src/features/invoices/api/useUpsertDedicatedInvoicePayment.tsx, src/features/invoices/api/useUpsertInvoice.tsx, src/features/invoices/invoiceSchemas.ts, src/providers/BusinessProvider/BusinessProvider.tsx, src/styles/index.scss, src/utils/form.ts
This PR creates schema/data management/form handling for invoice payments from the invoice detail view. 
Along the way, I also:
1. Created a `Drawer` variant of the modal to put the invoice payment form in.
2. Added a "discard changes" confirmation modal to ensure that users don't exit the invoice detail view without saving.
3. Moved "Edit invoice" to a hamburger dropdown... more polish coming on that later when there are more options.
4. Adjusted some existing modals to vertically align their name/close button.
=> feat: make invoice payments

src/components/DataTable/PaginatedTable.tsx, src/components/DataTable/dataTable.scss, src/components/Pagination/Pagination.tsx, src/components/ProfitAndLossDetailReport/ProfitAndLossDetailReport.tsx, src/components/ProfitAndLossDetailReport/profit_and_loss_detail_report.scss, src/components/VirtualizedDataTable/VirtualizedDataTable.tsx, src/components/VirtualizedDataTable/virtualizedDataTable.scss, src/components/ui/Table/table.scss, src/styles/pagination.scss
=> fix: alignment for virtualized table

src/components/ProfitAndLossDetailReport/ProfitAndLossDetailReport.tsx, src/components/VirtualizedDataTable/VirtualizedDataTable.tsx
=> default to false and make optional

package-lock.json, package.json
=> v0.1.107-alpha.2

src/components/Button/SubmitButton.tsx, src/components/MatchForm/MatchForm.tsx, src/components/Tabs/Tabs.tsx, src/components/Tabs/tabs.scss, src/components/Tasks/Tasks.tsx, src/components/Tasks/TasksList.tsx, src/components/Tasks/TasksListItem.tsx, src/components/Tasks/tasks.scss, src/components/Tasks/tasksMonthSelector.scss, src/styles/bank_transactions.scss, src/views/BookkeepingOverview/BookkeepingOverview.tsx
Fixes the following tickets: [LAY-1698](https://linear.app/layerfi/issue/LAY-1698/adjust-vertical-alignment-of-bookkeeping-tasks-and-pandl-visuals), [LAY-1699](https://linear.app/layerfi/issue/LAY-1699/transaction-categorization-match-suggestions-are-cut-off), [LAY-1700](https://linear.app/layerfi/issue/LAY-1700/increase-css-font-size-for-update-icon-in-accounting), [LAY-1702](https://linear.app/layerfi/issue/LAY-1702/improve-scrolling-experience-on-overview-page-with-tasks)
=> fix: dripos bookkeeping bugs

package-lock.json, package.json
=> v0.1.108-alpha.1

src/hooks/useAccountingConfiguration/useAccountingConfiguration.tsx, src/schemas/accountingConfiguration.ts
=> Fix account numbers
