- src/styles/accounting_overview.scss
- src/styles/profit_and_loss_detailed_charts.scss
1. Fix alignment of the PnL chart legend on small screens
2. Fix sizing of detailed charts
> fix: responsive sizing of detailed pnl charts

- src/styles/bank_transactions.scss
- src/styles/inputs.scss
Fix inputs' sizes in Bank Transaction form.
> fix: inputs size in bank transactions form

- src/api/layer.ts
- src/api/layer/linked_accounts.ts
- src/components/HoverMenu/HoverMenu.tsx
- src/components/LinkedAccountOptions/LinkedAccountOptions.tsx
- src/components/LinkedAccountPill/LinkedAccountPill.tsx
- src/components/LinkedAccountPill/index.tsx
- src/components/LinkedAccountThumb/LinkedAccountThumb.tsx
- src/components/LinkedAccounts/LinkedAccountsContent.tsx
- src/components/Pill/Pill.tsx
- src/contexts/LayerContext/LayerContext.tsx
- src/contexts/LinkedAccountsContext/LinkedAccountsContext.ts
- src/hooks/useLinkedAccounts/mockData.ts
- src/hooks/useLinkedAccounts/useLinkedAccounts.ts
- src/providers/LayerProvider/LayerProvider.tsx
- src/styles/hover-menu.scss
- src/styles/index.scss
- src/styles/linked_account_pill.scss
- src/styles/linked_accounts.scss
- src/styles/pill.scss
- src/styles/tasks.scss
- src/types/layer_context.ts
- src/types/linked_accounts.ts
Adds support for
1. In staging environments, breaking a connection
2. Unlinking connections
3. Displaying account status pills (connection broken / needs duplication confirmation)
4. Duplication confirmation/denial
5. Link repair flow
> Add Duplicate Account and Repair Connection UIs

- src/providers/LayerProvider/LayerProvider.tsx
We were using the `auth` local variable instead of using the reduced `state.auth`. This was fine for cases where we just refreshed the auth token, but this doesn't work when using a `businessAuthToken`, as there's no manual refreshing of credentials.
> use auth from state

- src/api/layer.ts
- src/api/layer/linked_accounts.ts
- src/hooks/useLinkedAccounts/useLinkedAccounts.ts
- Remove out of date comments
- Remove calls to `syncAccounts` since this endpoint is now rate-limited. Either move sync trigger to backend or replace with `updateConnectionStatus` to refresh connection statuses if and only if there actually is a broken account connection
> Account linking cleanup

- src/styles/component.scss
- src/views/Reports/Reports.tsx
Prevents this ^ from happening when screen enlarged enough or zoomed out
> fix max width on reports header actions

- src/components/ChartOfAccountsRow/ChartOfAccountsRow.tsx
Improve indentations in Chart of accounts table on mobile.
Before:
<br/>
<br/>
After:
> fix: chart of accounts indentation on mobile

- src/views/BankTransactionsWithLinkedAccounts/BankTransactionsWithLinkedAccounts.tsx
Allows us to show mobile bank transaction component in BankTransactionsWithLinkedAccounts
> allow mobile list on bank transactions with linked accounts

- src/components/Onboarding/ConnectAccount.tsx
- src/views/AccountingOverview/AccountingOverview.tsx
1. Add missing "Bell" icon the pending transactions badge.
2. Enable showing transactions to categorise in onboarding.
> feat: add bell icon to the onboarding step

- src/components/Onboarding/ConnectAccount.tsx
- src/components/TransactionToReviewCard/TransactionToReviewCard.tsx
- src/utils/bankTransactions.ts
- src/views/AccountingOverview/AccountingOverview.tsx
Use only current month to count number of transactions to review.
<br/>
<br/>
7 transactions to review in overall, but only 2 in June:
> feat: count only transactions to review from current month

- src/components/BankTransactionMobileList/BusinessForm.tsx
- src/components/BankTransactionMobileList/MatchForm.tsx
- src/components/BankTransactionMobileList/PersonalForm.tsx
- src/components/BankTransactionMobileList/SplitForm.tsx
Use regular button instead of Retry button, because it looks more logical and natural when combined with the error message displayed below the button.
> feat: regular button instead of retry button in mobile bank transactions

- src/components/BankTransactionMobileList/SplitForm.tsx
- src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx
Open numeric keyboard on mobile devices when user edits amount inputs.
> fix: open numeric keyboard on mobile for amount inputs

- src/components/Drawer/Drawer.tsx
- src/contexts/DrawerContext/DrawerContext.tsx
- src/hooks/useDrawer/useDrawer.tsx
- src/styles/bank_transactions.scss
- src/styles/bank_transactions_mobile_list.scss
- src/styles/date_month_picker.scss
- src/styles/drawer.scss
1. Adjust sizing of drawer for "tablets"
2. improve drawer's closing animation
3. limit the width of mobile bank transactions list
> feat: drawer for tablets

- src/components/BankTransactionMobileList/SplitForm.tsx
- src/components/CategorySelect/CategorySelect.tsx
- src/components/CategorySelect/CategorySelectDrawer.tsx
- src/styles/inputs.scss
Use drawer to select split's category in the Split form.
> feat: drawer for mobile splits

- src/components/TransactionToReviewCard/TransactionToReviewCard.tsx
Fix loading state of "Transactions to Review" card when user goes back to the view.
https://github.com/Layer-Fi/layer-react/assets/11715931/d87000d7-fc36-4db1-838b-77f064cc115d
> fix: loading state in transactions to review after return

- src/components/DateDayPicker/DateDayPicker.tsx
- src/components/DateMonthPicker/DateMonthPicker.tsx
- src/styles/date_month_picker.scss
Fix showing "Current" button in date pickers when component is small.
> fix: date picker mixing styling on different breakpoints

- src/components/ChartOfAccountsForm/ChartOfAccountsForm.tsx
- src/components/JournalForm/JournalForm.tsx
- src/styles/chart_of_accounts.scss
- src/styles/journal.scss
Use Cancel/Submit buttons below the form on mobile screens so it's easier to reach by thumb and user doesn't have to scroll back up to see buttons on long forms.
> feat: use buttons below the form on mobile

- src/components/LinkedAccounts/LinkedAccountsContent.tsx
- src/styles/linked_accounts.scss
Just in time for this to no longer matter (since it is no longer possible to get an account marked as needing confirmation), I have fixed the hover menu that is shown on linked accounts.
> fix confirm account dropdown

- src/components/ProfitAndLossDetailedCharts/DetailedChart.tsx
- src/components/ProfitAndLossDetailedCharts/DetailedTable.tsx
- src/config/charts.ts
> fix: Profit and Loss - chart colors - use similar colors for same categories

- src/styles/bank_transactions.scss
In Bank transactions table, make column widths more fixed so it doesn't jump around when toggling "To review" and "Categorized"
https://github.com/Layer-Fi/layer-react/assets/11715931/0c4025fd-d966-47a6-ae2a-32e1445a6117
> fix: bank transactions table column widths

- src/components/ProfitAndLossDetailedCharts/ProfitAndLossDetailedCharts.tsx
Hide Back button from PnL detailed charts on overview views.
<br/>
<br/>
> fix: hide back button in detailed charts

- src/components/DatePicker/DatePicker.tsx
- src/components/LinkedAccountThumb/LinkedAccountThumb.tsx
- src/hooks/useLinkedAccounts/mockData.ts
- src/styles/linked_accounts.scss
- src/types/linked_accounts.ts
Requires this other PR to be merged first: https://github.com/Layer-Fi/api/pull/778
<br /> <br />
Shorten long account names to prevent the name affecting the width of the card
<br /> <br />
Prevent user from picking a date in the future using the date picker
<br /> <br />
Prevent Add Account button from getting squished when 5+ account cards
> Show loading status on linked accounts / fix linked account tile size

- src/components/BankTransactionMobileList/BusinessForm.tsx
- src/components/BankTransactions/BankTransactions.tsx
- src/components/BankTransactions/DataStates.tsx
- src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx
- src/components/LinkedAccountThumb/LinkedAccountThumb.tsx
- src/styles/linked_accounts.scss
- src/styles/variables.scss
1. Prevent non-numeric-input in split amount fields
^^old picture from ticket
New Behavior: if the user tries to type a non-number or more than one period, their keypress does nothing
<br /> <br />
2. Hide refresh button on Transactions empty state
<br /> <br />
3. Show loading message _and_ refresh button when at least one account is in the syncing state
<br /> <br />
4. Change category button to "outline" style <br />
<br /> <br />
5. New ui for account card in loading state
> Prevent non-numeric-input in split amount fields / transaction empty state UX updates

- src/components/TasksList/TasksList.tsx
- src/components/TasksListItem/TasksListItem.tsx
Three changes
1. Don't re-order tasks after completion: completed ones don't go to the bottom. This has nasty UX side effects where you can "complete" all your tasks and not realize there are multiple pages (it's not super obvious), so two additional changes...
2. Upon page open, we go to the first page with incomplete tasks.
3. Upon completing all the tasks on a page, automatically change to the next page.
> Tasks navigation

- src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx
I replaced `parseMoney` with my own parsing function, not realizing that `parseMoney` also converted dollars to cents
> Fix splits dollars to cents

- src/components/ProfitAndLossSummaries/ProfitAndLossSummaries.tsx
- src/components/ProfitAndLossView/ProfitAndLossView.tsx
- src/views/AccountingOverview/AccountingOverview.tsx
- src/views/BookkeepingOverview/BookkeepingOverview.tsx
Make PnL summary cards not clickable by default.
Using:
```
<ProfitAndLoss.Summaries />
```
Using:
```
<ProfitAndLoss.Summaries actionable />
```
https://github.com/user-attachments/assets/aafc86d6-8159-47c9-ad4d-3bf7fc12555d
> feat: pnl summaries cards not clickable by default

- src/components/ProfitAndLossChart/ProfitAndLossChart.tsx
- src/types/profit_and_loss.ts
Follow-up to `totalExpenses` fix
> fix: total expenses

- src/components/ProfitAndLossRow/ProfitAndLossRow.tsx
- src/components/ProfitAndLossTable/ProfitAndLossTable.tsx
- src/styles/profit_and_loss.scss
Fix styling of row nested deeper than level `1` in Profit and Loss table.
Questions:
1. Do we want to support `maxDepth` through `ProfitAndLossTable` props?
2. only first level auto-expanded? or all auto-expanded?
https://github.com/user-attachments/assets/e6fe5228-e3f9-4456-8d1c-709033bbf710
> fix: styling for deeper levels in pnl table

- package.json
- src/components/LinkedAccountThumb/LinkedAccountThumb.tsx
- src/types/bank_transactions.ts
- src/types/categories.ts
Was getting an unhandled error for a business with transactions with null categorization flows and realized that this was not accounted for on the front-end.
Also included in this PR: falling back to the linked bank account name when the institution is null
> Handle null categorization_flow + account institution

- src/components/BalanceSheet/BalanceSheet.tsx
- src/components/DatePicker/DatePicker.tsx
- src/styles/bank_transactions.scss
Data was not fetch on every date selection on BalanceSheet page, because DatePicker didn't call `onChange` on every date selection. The problem was with wrong dates comparison.
https://github.com/user-attachments/assets/7b469429-afe6-4a79-9e7f-dc8a7158f9c2
> fix: datepicker not calling onchange on every change

- src/components/Toggle/Toggle.tsx
Toggle thumb size and position was not updated when all options are disabled.
> fix: toggle thumb not updated when options disabled

- src/components/BankTransactionsLoader/BankTransactionsLoader.tsx
- src/components/BankTransactionsTable/BankTransactionsTable.tsx
- src/components/SkeletonTableLoader/SkeletonTableLoader.tsx
- src/styles/loader.scss
1. Drop skeleton loaders from bank transaction table when any data is loaded
2. improve structure of loaders
https://github.com/user-attachments/assets/81fc6a4a-9918-4647-801a-9cc5375c0314
https://github.com/user-attachments/assets/76b4aac2-6313-4392-92f6-8acb52848956
https://github.com/user-attachments/assets/c59ce0a8-3d62-4bf7-b158-a8f0e2709dc5
> feat: drop bank transaction loaders when data loaded

- src/providers/LayerProvider/LayerProvider.tsx
1. I added console.logs and you can see that the `onSuccess` triggers only on page load, `useEffect` triggers immediately after that page load _and_ upon renavigating. This _is_ why it works.
2. I tried the `revalidateOnMount` param and that _also_ would have solved the issue by forcing a re-request to load the query again. Inferior for our use case, as we don't expect the values to have changed between navigating away and back, so no revalidation is necessary.
> use returned SWR value always when it changes

- src/components/BankTransactions/BankTransactionsHeader.tsx
- src/components/Button/RetryButton.tsx
- src/styles/bank_transactions.scss
- src/styles/bank_transactions_mobile_list.scss
- src/styles/button.scss
Restyle bank transactions header including download button.
Further improvement can/will be done with other PRs:
1. Show spinner on download button
2. Reorganize buttons into two rows
https://github.com/user-attachments/assets/415da0ee-f311-494a-b2f5-041cc73611e6
https://github.com/user-attachments/assets/8a1302f0-e159-454e-bc54-c957db0a96a7
https://github.com/user-attachments/assets/cdafa1ba-fb42-43f0-bddc-6daf8635fed7
https://github.com/user-attachments/assets/1d50301b-cefd-4a22-9028-d2568da8e2e7
> feat: restyle download button on bank transactions

- src/styles/bookkeeping_overview.scss
- src/views/AccountingOverview/AccountingOverview.tsx
- src/views/BookkeepingOverview/BookkeepingOverview.tsx
Wide screen:
Narrow screen:
Also included: Profit and Loss details charts toggle now defaults to Expenses instead of Revenue
> responsive bookkeeping overview

- src/components/ProfitAndLossDetailedCharts/DetailedChart.tsx
- src/components/ProfitAndLossDetailedCharts/DetailedTable.tsx
- src/hooks/useProfitAndLoss/useProfitAndLoss.tsx
- src/styles/profit_and_loss.scss
- src/styles/profit_and_loss_detailed_charts.scss
Add "Uncategorized" to P&L detailed charts.
https://github.com/user-attachments/assets/b7e2595b-16c4-4818-b158-6d6997fa063e
EDIT:
Detailed charts are using "dots" in a background pattern of the pie:
> feat: add uncategorized to detailed charts

- src/styles/variables.scss
Add `.Layer__variables` to allow use CSS variables without using `.Layer__component`.
Without  `.Layer__variables`:
With `.Layer__variables`:
> feat: add layer__variables class

- src/components/ProfitAndLossTable/ProfitAndLossTableComponent.tsx
- src/components/ProfitAndLossTable/ProfitAndLossTableWithProvider.tsx
- src/components/ProfitAndLossTable/index.tsx
- src/components/ProfitAndLossView/ProfitAndLossView.tsx
- src/views/Reports/Reports.tsx
Previously, it was necessary to have a `TableProvider` before using the profit and loss table. This requirement has now been removed. Instead, the `ProfitAndLoss.Table` is directly exported and can be used without needing a separate `TableProvider`.
> fix: add profil and loss provider to export

- src/components/CategorySelect/CategorySelect.tsx
Now shows a header for each top-level account, and all leaf accounts under each
> fix flatten categories

- src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx
- src/hooks/useBankTransactions/useBankTransactions.tsx
Fixes: LAY-947 (partially)- backend changes needed to make categorization & matching idempotent
> dont call match endpoint for confirming existing matched transfers

- src/components/BankTransactions/BankTransactions.tsx
Bank transactions: Set page number to `1` when filters change.
https://github.com/user-attachments/assets/cf345b32-f7d0-4844-b299-fcb153117a7d
> fix: reset bank transactions page on filters change

- package-lock.json
- src/components/BankTransactionMobileList/BusinessForm.tsx
- src/components/BankTransactionRow/BankTransactionRow.tsx
- src/components/LedgerAccountEntryDetails/LedgerAccountEntryDetails.tsx
- src/hooks/useBankTransactions/useBankTransactions.tsx
1. Fallback to transaction description if counterparty is null
2. Replace Approve/Save copy with "Confirm" (see below)
> Small copy changes

- src/utils/format.ts
Allow for cents in Journal form. It doesn't allow for negative values and use only 2 decimal places.
https://github.com/user-attachments/assets/a7f43e3b-f64d-4556-aa8e-78878e387e43
> fix: allow for cents in journal

- src/components/Badge/Badge.tsx
- src/components/ProfitAndLoss/ProfitAndLoss.tsx
- src/components/ProfitAndLossChart/ChartStateCard.tsx
- src/components/ProfitAndLossChart/ProfitAndLossChart.tsx
- src/components/ProfitAndLossHeader/ProfitAndLossHeader.tsx
- src/components/ProfitAndLossHeader/index.tsx
- src/components/ProfitAndLossView/ProfitAndLossView.tsx
- src/components/SyncingBadge/SyncingBadge.tsx
- src/components/SyncingBadge/index.tsx
- src/icons/BarChart2.tsx
- src/icons/Loader.tsx
- src/styles/badge.scss
- src/styles/charts.scss
- src/styles/component.scss
- src/styles/profit_and_loss.scss
- src/styles/variables.scss
- src/views/AccountingOverview/AccountingOverview.tsx
- src/views/BookkeepingOverview/BookkeepingOverview.tsx
Support syncing and no-data states on profit and loss chart.
1. NO syncing and NO data
_Bars are just gray placeholders with no action on click_
2. NO syncing and data
3. Syncing and NO data
_Bars have same animation as in loading state_
4. Syncing and data
> feat: profit and loss chart - sync and empty states

- src/components/ProfitAndLossDownloadButton/ProfitAndLossDownloadButton.tsx
- src/components/ProfitAndLossReport/ProfitAndLossReport.tsx
`npm run build` was not generating `index.d.ts` because some interfaces weren't being exported properly.
> fix npm run build

- package.json
- src/components/ChartOfAccounts/ChartOfAccounts.tsx
- src/components/ChartOfAccountsTable/ChartOfAccountsTable.tsx
- src/components/ChartOfAccountsTable/ChartOfAccountsTableWithPanel.tsx
- src/components/ProfitAndLossDownloadButton/ProfitAndLossDownloadButton.tsx
- src/components/ProfitAndLossReport/ProfitAndLossReport.tsx
- src/views/GeneralLedger/GeneralLedger.tsx
When setting is enabled, it adds an uneditable state (with a tooltip) for accounts with a stable name, i.e. accounts created by  the system.
> flag for making template accounts uneditable

- package.json
- src/components/CategorySelect/CategorySelect.tsx
Prevent multiple options being shown as selected, move check box for selected to the left of the category name, move the tooltip to the right side of the option.
> Fix category select

- src/api/layer.ts
- src/api/layer/bankTransactions.ts
- src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx
- src/components/Tasks/Tasks.tsx
- src/types/bank_transactions.ts
- src/types/general.ts
- Add endpoints for get document and archive document
- Add query param for content-disposition for documents (not actually needed but is an option now)
- Add transaction metadata and list of document IDs to transaction object
- Add function for opening document image in new tab (need to decide how to handle PDFs)
> open receipt in new tab, add new fields + endpoints

- src/components/JournalTable/JournalTable.tsx
Journal table rows expanded by default.
[LAY-1033](https://linear.app/layerfi/issue/LAY-1033/default-expand-journal-list)
> fix: journal rows expanded by default

- src/components/JournalTable/JournalTable.tsx
Rename default column name: "Account" to "Account Name" in Journal table.
[LAY-1029](https://linear.app/layerfi/issue/LAY-1029/journal-entry-creation-rename-date-effective-date)
> fix: rename account to account name in journal

- src/components/JournalEntryDetails/JournalEntryDetails.tsx
- src/components/JournalForm/JournalFormEntryLines.tsx
Move "Debit" before "Credit" in Journal form and details.
[LAY-1027](https://linear.app/layerfi/issue/LAY-1027/debit-line-items-should-be-shown-above-credit-line-items)
[LAY-1028](https://linear.app/layerfi/issue/LAY-1028/journal-entry-creation-debits-before-credits)
> fix: debit before credit in journal

- src/components/Journal/Journal.tsx
- src/components/JournalTable/JournalTable.tsx
- src/components/JournalTable/JournalTableWithPanel.tsx
Sort Journal by `entry_at` and display `entry_at` in the Date column.
> feat: journal - use entry_at as date

- src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx
1. Fix disappearing receipts on page resize.
2. Allow to delete failed uploads
3. Show "open" button only for images
[LAY-1039](https://linear.app/layerfi/issue/LAY-1039/errored-uploads-call-all-uploads-to-disappear-when-adjusting-the-grid)
[LAY-1038](https://linear.app/layerfi/issue/LAY-1038/allow-deletion-of-documents-that-failed-to-upload)
[LAY-1037](https://linear.app/layerfi/issue/LAY-1037/hide-view-receipt-button-for-non-images)
https://github.com/user-attachments/assets/358a88be-6287-441b-8b44-b5de9d0462cd
https://github.com/user-attachments/assets/026bf7c5-a5e7-4609-8603-8408faf5213e
> fix: disappearing receipts on screen resize

- src/components/JournalEntryDetails/JournalEntryDetails.tsx
- src/components/LedgerAccountEntryDetails/LedgerAccountEntryDetails.tsx
Fix Reversal value formatting
[LAY-1021](https://linear.app/layerfi/issue/LAY-1021/reversal-text-sizing-is-unstyled)
> fix: formatting reversal value in journal entry details

- bin/build.js
A breaking change was made in [esbuild v0.18.0](https://github.com/evanw/esbuild/blob/main/CHANGELOG-2023.md#0180) that dropped inference of `target` from the supplied tsconfig file.
> fix(build): force target ES2016

- src/components/DatePicker/ModeSelector/date-picker-mode-selector.scss
Fix warning about using `end` value for `justify-content`.
Before:
```
Compiled with warnings.
Warning
(1016:3) autoprefixer: end value has mixed support, consider using flex-end instead
Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
WARNING in ../components/dist/styles/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!../components/dist/styles/index.css)
Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning
(1016:3) autoprefixer: end value has mixed support, consider using flex-end instead
webpack compiled with 1 warning
No issues found. …
```
> fix: compile warning - flex-end

- src/components/LinkedAccounts/LinkedAccountItemThumb.tsx
- src/hooks/useLinkedAccounts/mockData.ts
- src/hooks/useLinkedAccounts/useLinkedAccounts.ts
- src/types/linked_accounts.ts
This change to the components will allow us to safely deprecate the value in the API.
> refactor: remove reference to `requires_user_confirmation_as_of`

- package-lock.json
- src/hooks/useQuickbooks/useQuickbooks.ts
When QB redirects back to the Layer app, there was a race condition between fetching the auth token and fetching some quickbooks data. This ensures we have the auth token before querying the quickbooks data
> Fix QB OAuth bug

- src/api/layer/journal.ts
- src/components/BankTransactions/BankTransactions.tsx
- src/components/ChartOfAccountsTable/ChartOfAccountsTable.tsx
- src/components/DatePicker/DatePicker.tsx
- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/Input/MultiSelect.tsx
- src/components/Input/Select.tsx
- src/components/ProfitAndLossChart/Indicator.tsx
- src/components/ProfitAndLossChart/ProfitAndLossChart.tsx
- src/components/ProfitAndLossCompareOptions/ProfitAndLossCompareOptions.tsx
- src/components/ProfitAndLossDetailedCharts/DetailedTable.tsx
- src/components/Tooltip/Tooltip.tsx
- src/hooks/useProfitAndLoss/useProfitAndLossLTM.tsx
- src/hooks/useProfitAndLoss/useProfitAndLossQuery.tsx
- src/hooks/useReceipts/useReceipts.ts
- src/types/chart_of_accounts.ts
- src/types/general.ts
This is part of an effort to get us down to a few linter errors as possible. Once we can get it to zero, then we can fail the production build
> chore: remove many uses of explicit `any`

- bin/build.js
In order to preserve backward compatibility, we need to only be copying style files to a new location. Eventually, we can make this just an `mv`.
> fix: preserve compatibility by copying styles

- bin/build.js
- package-lock.json
- package.json
Our `exports` field limits the ability of consumers to import from "deep" within our package.
> build: expose legacy style import through `exports` field in package.json

- src/api/layer/bankTransactions.ts
- src/components/BankTransactionMobileList/BankTransactionMobileForms.tsx
- src/components/BankTransactionMobileList/BankTransactionMobileListItem.tsx
- src/components/BankTransactionMobileList/BusinessForm.tsx
- src/components/BankTransactionMobileList/SplitAndMatchForm.tsx
- src/components/BankTransactionMobileList/SplitForm.tsx
- src/styles/file_thumb.scss
- For transactions in mobile view, only show categorization to self-serve clients
- On mobile web, downloading an attachment will not change the browser URL (due to `content-disposition: attachment`)
> fix: bank transactions in mobile + bookeeping view consistency

- src/api/layer/balance_sheet.ts
- src/api/layer/statement-of-cash-flow.ts
- src/components/BalanceSheet/BalanceSheet.tsx
- src/components/BalanceSheet/download/BalanceSheetDownloadButton.tsx
- src/components/BalanceSheet/download/useBalanceSheetDownload.ts
- src/components/ChartOfAccounts/ChartOfAccounts.tsx
- src/components/Journal/Journal.tsx
- src/components/StatementOfCashFlow/StatementOfCashFlow.tsx
- src/components/StatementOfCashFlow/download/CashflowStatementDownloadButton.tsx
- src/components/StatementOfCashFlow/download/useCashflowStatementDownload.ts
- src/components/ui/Stack/Stack.tsx
- src/components/ui/Stack/stack.scss
- src/components/utility/InvisibleDownload.tsx
- src/components/utility/index.scss
- src/hooks/useElementViewSize/index.ts
- src/hooks/useElementViewSize/useElementViewSize.tsx
- src/styles/index.scss
- src/utils/delay/runDelayed.ts
- src/utils/request/toDefinedSearchParameters.ts
- src/views/Reports/Reports.tsx
This change adds a button at the top of the balance sheet and cashflow reports to download them in CSV form. The goal is to reach parity with the Income Statement.
> feat: download button for casflow statement and balance sheet

- src/styles/tasks.scss
When the overflow is hidden, the element will not get any taller than its sibling (the main content). This is a major issue when there are more than a few tasks.
> fix: `BookkeeppingTasks` component should scroll when there are many tasks

- eslint.config.mjs
- src/components/ProfitAndLossChart/Indicator.tsx
When refactoring for React `rules of hooks`, I broke a component that relied on being forced to re-render.
> fix: chart `Indicator` needs to force re-render

- src/views/GeneralLedger/GeneralLedger.tsx
We added this variable into the `<ChartOfAccounts />` component, but didn't elevate the prop to the `chartOfAccountsOption` slot props field in the `GeneralLedgerView` which was a little silly.
> Expose `showAddAccountButton` in GL's `chartOfAccountsOptions` slot

- src/components/BalanceSheet/BalanceSheet.tsx
- src/components/BalanceSheetDatePicker/BalanceSheetDatePicker.tsx
- src/components/BalanceSheetDatePicker/index.tsx
- src/components/BankTransactions/BankTransactionsHeader.tsx
- src/components/ChartOfAccountsDatePicker/ChartOfAccountsDatePicker.tsx
- src/components/DatePicker/DatePicker.tsx
- src/components/DatePicker/DatePickerOptions.tsx
- src/components/DatePicker/ModeSelector/DatePickerModeSelector.tsx
- src/components/JournalForm/JournalForm.tsx
- src/components/LinkedAccounts/AccountFormBox/AccountFormBox.tsx
- src/components/ProfitAndLoss/ProfitAndLoss.tsx
- src/components/ProfitAndLossChart/ProfitAndLossChart.tsx
- src/components/ProfitAndLossDatePicker/ProfitAndLossDatePicker.tsx
- src/components/StatementOfCashFlow/StatementOfCashFlow.tsx
- src/components/StatementOfCashFlow/datePicker/StatementOfCashFlowDatePicker.tsx
- src/components/TasksHeader/TasksHeader.tsx
- src/hooks/useAuth.ts
- src/hooks/useProfitAndLoss/useProfitAndLoss.tsx
- src/hooks/useProfitAndLossComparison/useProfitAndLossComparison.tsx
- src/hooks/useQuickbooks/useQuickbooks.ts
- src/providers/GlobalDateStore/GlobalDateStoreProvider.tsx
- src/providers/GlobalDateStore/useGlobalDateRangePicker.ts
- src/providers/LayerProvider/LayerProvider.tsx
- src/utils/array/getArrayWithAtLeastOneOrFallback.ts
- src/utils/switch/safeAssertUnreachable.ts
- src/utils/zustand/useStoreWithDateSelected.ts
- src/views/AccountingOverview/AccountingOverview.tsx
- src/views/ProjectProfitability/ProjectProfitability.tsx
- src/views/Reports/reportTypes.ts
**Linear**: LAY-1128
The three major reports - P&L, Balance Sheet, and Cash Flow - now share common date state.
After a user adjusts the date range for viewing one report, they will preserve this same date range for another report. Since the balance sheet is a point in time, it is simply the end of the defined range.
- The Profit and Loss Comparison does not correctly handle non-month time periods. This is already an issue and will be attacked in follow-on work.
- The Profit and Loss Chart still displays reasonably, but the selected range outline _only_ highlights the first month in the range. I don't think it's reasonable to fold-in even more changes to manage that chart in special situations.
> [LAY-1128] feat: unify all major date pickers through global state

- src/api/layer/categories.ts
- src/components/JournalForm/JournalFormEntryLines.tsx
- src/hooks/categories/useAllCategories.ts
**Linear**: LAY-1153
We are now loading journal entries from the categories endpoint.
If a user doesn't touch the date selector at all, no date has been set.
> [LAY-1153] fix: load all categories for manual journal entries

- src/components/DueStatus/DueStatus.tsx
- src/components/DueStatus/due_status.scss
- src/styles/index.scss
To make large Bills PR easier to review, this PR adds `<DueStatus />` component used on Bills pages.
- `<DueStatus />` component
```
<div style={{ padding: 12 }}>
<DueStatus dueDate={new Date()} paidAt={new Date()} paid={true} />
</div>
<div style={{ padding: 12 }}>
<DueStatus dueDate={sub(new Date(), { days: 3 })} />
</div>
<div style={{ padding: 12 }}>
<DueStatus dueDate={sub(new Date(), { days: 13 })} />
</div>
<div style={{ padding: 12 }}>
<DueStatus dueDate={sub(new Date(), { days: -1 })} />
</div>
<div style={{ padding: 12 }}>
<DueStatus dueDate={sub(new Date(), { days: -4 })} />
</div>
```
> feat: due status

- src/components/Button/SubmitButton.tsx
- src/components/DatePicker/DatePicker.tsx
- src/components/Header/HeaderCol.tsx
- src/components/Input/StaticValue.tsx
- src/components/TableCell/TableCell.tsx
- src/components/Toggle/Toggle.tsx
- src/components/Typography/ErrorText.tsx
- src/components/Typography/Text.tsx
- src/styles/header.scss
- src/styles/inputs.scss
- src/styles/table.scss
- src/styles/typography.scss
- src/types/table.ts
This PR brings a chunk of smaller changes to existing components that will be then used with the Bills.
This is a part of efforts aiming to minify large Bills PR.
- allow to control button variant in `SubmitButton`
- make DatePicker's `maxDate` optional
- allow to use `HeaderCol` without paddings
- add `StaticValue` - it can be use as a replacement to the (disabled) inputs, ie. on summary view after submitting the form when we want to keep similar layout, but showing disabled input doesn't look right. `StaticValue` has similar sizings as `Input`
- add `nowrap` prop to `TableCell` so the cell content is not wrapped
- fix `Toggle` state management
- add `ellipsis` prop to `Text` so it sets `text-overflow: ellipsis`
- add `status` prop to `Text` so we can easily set basic colors like error, …
> feat: extending components - for bills

- src/hooks/useAuth.ts
See [this diagram](https://swr.vercel.app/docs/advanced/understanding#key-change--previous-data) to understand the design of SWR.
This change is defensive and motivated by some issues surfaced by testing document upload with Carry.
If a new business access token is requested by their outer SWR (not controlled by us), then our `useAuth` hook could momentarily return `data === undefined` before it resolves with the new token. Since all other data-loading is derived from `useAuth`, we can potentially avoid flickering of other SWR keys by continuing to pass the stale values.
> fix: `keepPreviousData` on our useAuth hook

- src/api/layer/profit_and_loss.ts
- src/components/ProfitAndLossCompareOptions/ProfitAndLossCompareOptions.tsx
- src/hooks/useProfitAndLossComparison/useProfitAndLossComparison.tsx
- src/types.ts
- src/types/profit_and_loss.ts
- src/utils/array/getArrayWithAtLeastOneOrFallback.ts
- src/utils/array/range.ts
This change is intended to help @tomaszantas build-out year picking abilities.
I have run various configurations of PNL comparison filtering locally to verify that I have not introduced a regression.
> fix: improve types for `compareProfitAndLoss`

- src/components/BankTransactionMobileList/BankTransactionMobileForms.tsx
- src/components/BankTransactionMobileList/SplitAndMatchForm.tsx
The `showCategorization` prop wasn't passed down to the Split form in Bank Transactions mobile list.
- pass the `showCategorization` prop down to the Split form
- minor lint fixes in touched files
**Before**
https://github.com/user-attachments/assets/680892fd-521d-4355-ab34-7601399468bf
**After**
https://github.com/user-attachments/assets/21834f4d-b6f2-4371-b0fb-0c0e053996ef
> fix: missing split form on bank transactions mobile list

- src/components/Toggle/Toggle.tsx
Replace `activeOption` state with `useMemo`
https://github.com/user-attachments/assets/8190f747-16d0-40d9-9d85-9eda712b4a06
> fix: refactor active state in toggle

- src/api/layer/authenticated_http.ts
- src/components/Button/RetryButton.tsx
- src/components/Toast/Toast.tsx
- src/components/Typography/Text.tsx
- src/config/general.ts
- src/styles/toast.scss
- src/styles/typography.scss
- src/types/table.ts
- src/utils/format.ts
- src/utils/vendors.ts
Selected changes from the Bills PR #357 are moved here to make the original PR easier to review.
- fix: pass the API error message down to the JS API Error object
- show tooltip on `RetryButton` if `error` message prop provided
- add `success` styling to Toast
- add `disabled` (muted) styling to the Text
- add `DATE_FORMAT_SHORT` to config
- add `main` variant for the Table Row - such rows use lighter background by default
- allow to `vendor?.external_id` if `individual_name` and `company_name` are not provided when we want to show vendor's name in UI
Success Toast:
Retry Button with the error message in the tooltip:
> feat: small changes from bills pr

- src/components/LedgerAccount/LedgerAccountRow.tsx
- src/components/LedgerAccountEntryDetails/LedgerAccountEntryDetails.tsx
- src/types/journal.ts
- src/utils/journal.ts
We had a bug where we were using the _line item id_ and calling it the journal id number by accident, leading to situations like this 
Notice the journal id # in the table doesn't match the journal entry number on the right bar!
I've introduced a dedicated method (and separated out the acceptable argument types so type safety is enforced) to get the _entry_ numbers from line items, not the line item id.
> dedicated lineEntryNumber method

- src/components/ProfitAndLoss/ProfitAndLoss.tsx
- src/components/ProfitAndLossChart/Indicator.tsx
- src/components/ProfitAndLossChart/ProfitAndLossChart.tsx
- src/hooks/useProfitAndLoss/index.tsx
This change is intended to reduce confusion when a custom date range is selected.
> fix: (sometimes) hide P&L Summary Chart "Indicator"

- src/utils/bookkeeping/isCategorizationEnabled.ts
This is a fast-follow based on an internal testing session. When bookkeeping is paused, this is the equivalent of a user no longer being enrolled in the service (and they should have full control).
> fix: `BOOKKEEPING_PAUSED` should allow users to categorize

- src/components/LinkedAccounts/AccountFormBox/AccountFormBox.tsx
- src/components/LinkedAccounts/ConfirmationModal/LinkedAccountToConfirm.tsx
- src/components/ui/Checkbox/Checkbox.tsx
- src/components/ui/Checkbox/checkbox.scss
- src/components/ui/Modal/modal.scss
- src/styles/internal_variables.scss
- src/types/linked_accounts.ts
- change the default modal size 
- add success and dark variations to the checkbox
- add large and small variations to the checkbox
- add optional tooltip to the checkbox (ie. can be used to explain why checkbox is disabled)
Modal default size before:
Modal default size after:
Checkboxes:
> feat: modal default size, checkbox variants

- src/components/LinkedAccounts/OpeningBalanceModal/OpeningBalanceModal.tsx
- src/components/ui/Modal/Modal.tsx
- src/components/ui/Modal/modal.scss
It seems like the Modal was unintentionally made especially small.
This screenshot shows how the modal will appear (embedded within a customer's UI) at the adjusted size.
> fix: Modal default size is far too small

- src/hooks/useAuth.ts
This was added by me at one point, but it causes a bit too much flickering in dev mode because we can't ensure a stable result.
> fix: remove `revalidateOnFocus` from `useAuth` hook

- src/components/ProfitAndLossDetailedCharts/DetailedChart.tsx
- src/components/ProfitAndLossDetailedCharts/DetailedTable.tsx
- src/utils/profitAndLossUtils.ts
Previously we dropped negative values entirely out of the detail charts.
Now, we're going to include the negative values in the detail charts so they affect the total and show up in the table, but exclude them from percentage calculations so we don't have nonsensical numbers.
> include negative values in table and total, but not in percentages and pie chart

- src/utils/request/toDefinedSearchParameters.ts
This change is inspired by #519. It will influence our cashflow statement and balance sheet queries.
> fix: use ISO `full-date` when transforming search parameters

- src/hooks/useProfitAndLossComparison/useProfitAndLossComparison.tsx
- src/hooks/useProfitAndLossComparison/utils.ts
- src/types/profit_and_loss.ts
Accidentally been dropping this structure parameter when we formatted the tag filter body. This was causing us to not have any structure in the request, which I just found testing locally. 
The only customer who uses this functionality hadn't bumped to a version that dropped the structure, so fortunately, no client effects.
> include structure in processed body

- src/components/TasksMonthSelector/TasksMonthSelector.tsx
We had a user reporting that they couldn't click on months with tasks. We have a couple theories on what could have been messed up in the local state to cause this, but safest path forward: if there are tasks in a month, it should always be clickable. Right now, if that month is before activation time or after the current month, you can't!
> always allow clicking on months with any tasks

- src/components/ProfitAndLossChart/ProfitAndLossChart.tsx
If the only data you had were uncategorized transactions, the pnl summaries chart would display 'No data yet', because `anyData` wasn't counting uncategorized inflows/outflows
now it is counting uncategorized inflows/outflows
> fix pnl chart- not missing data

- src/api/layer.ts
- src/api/layer/bankTransactions.ts
- src/components/BankTransactions/BankTransactions.tsx
- src/components/ProfitAndLossSummaries/ProfitAndLossSummaries.tsx
- src/contexts/BankTransactionsContext/BankTransactionsContext.tsx
- src/hooks/useBankTransactions/useAugmentedBankTransactions.tsx
- src/hooks/useBankTransactions/useBankTransactions.ts
- src/utils/request/toDefinedSearchParameters.ts
This is the second step in a series of changes intended to unblock transaction search. In the next PR, I will add the query-parameter required for search.
> fix: extract `useBankTransactions` into a pure hook

- package-lock.json
- package.json
- src/components/Tasks/Tasks.tsx
- src/components/Tasks/container/TasksEmptyContainer.tsx
- src/components/Tasks/container/tasksEmptyContainer.scss
- src/components/Tasks/tasks.scss
- src/components/utility/ConditionalBlock.tsx
- src/hooks/bookkeeping/periods/useBookkeepingPeriods.ts
- src/hooks/bookkeeping/useBookkeepingStatus.ts
- src/utils/bookkeeping/bookkeepingStatusFilters.ts
The `Bookkeeping Tasks` section appears to hang for businesses that are not enrolled in bookkeeping.
This fix has two major components:
- Churned bookkeeping businesses can still view their old tasks
- If a business is not enrolled, they will receive a reasonable inactive state.
> [LAY-1254] fix: add an empty state for business not enrolled in bookkeeping

- src/api/layer/tasks.ts
- src/components/BookkeepingStatus/BookkeepingStatusReportRow.tsx
- src/components/Tasks/TasksList.tsx
- src/components/Tasks/TasksListItem.tsx
- src/components/Tasks/TasksListMobile.tsx
- src/components/Tasks/TasksMonthSelector.tsx
- src/components/Tasks/TasksPending.tsx
- src/components/Tasks/types.ts
- src/hooks/bookkeeping/periods/useBookkeepingPeriods.ts
- src/hooks/bookkeeping/periods/useBookkeepingYearsStatus.ts
- src/types/tasks.ts
- src/utils/bookkeeping/tasks/bookkeepingTasksFilters.ts
- src/utils/bookkeeping/tasks/getBookkeepingTaskStatusIcon.tsx
**Motivation** - the `periods` endpoint is returning `ARCHIVED` tasks. It has not been our attention to show archived tasks.
> fix: filter out `COMPLETED` and `ARCHIVED` at the source

- package-lock.json
- package.json
- src/components/BookkeepingStatus/BookkeepingStatus.tsx
- src/components/BookkeepingStatus/BookkeepingStatusDescription.tsx
- src/components/BookkeepingStatus/utils.tsx
- src/components/Tasks/TaskStatusBadge.tsx
- src/components/Tasks/TasksMonthSelector.tsx
- src/components/Tasks/TasksPending.tsx
This fix is instead to supersede #551. It includes a partial fix for LAY-1255, as periods in review will more aggressively prompt with incomplete tasks.
> [LAY-1253] fix: disable selecting not purchased periods

- package-lock.json
- package.json
- src/hooks/useKeepInMobileViewport.tsx
- src/views/BookkeepingOverview/BookkeepingOverview.tsx
- src/views/BookkeepingOverview/useKeepInMobileViewport.tsx
This PR adds hook observing `upper` element size and adjusts the page scroll to keep the `target` in the same spot of the viewport.
The usage:
```tsx
const { upperContentRef, targetElementRef, upperElementInFocus } = useKeepInMobileViewport()
return (
<>
<div ref={upperContentRef} onPointerEnter={() => upperElementInFocus.current = true}>
{...}
</div>
<div ref={targetElementRef} onPointerEnter={() => upperElementInFocus.current = false}>
{...} 
</div>
</>
)
```
---
To discuss:
We can leverage this into more reusable component, something like this:
```tsx
import { StickyMobileScroll } from '../components/StickyMobileScroll'
return (
<StickyMobileScroll upperElement={<div>...</div>}>
<div>Target element</div>
</StickyMobileScroll>
}
```
...and add prop for which we disable behavior. …
> fix: prevent jumping layout in bookkeeping overview

- src/components/Tasks/TasksList.tsx
- src/components/Tasks/TasksListMobile.tsx
- src/hooks/array/usePaginatedList.ts
The pagination of the tasks lists need to anticipate a dynamic list size. This occurs most often when switching between active periods (as the list component is not unmounted and remounted on this change).
> [LAY-1266] fix: prevent pinning to unreachable pages in bookkeeping tasks component

- package-lock.json
- package.json
This is motivated by fixing a customer issue with `recharts` loading. It is still unclear if the version upgrade will have any notable effect.
> upgrade: `recharts` on latest version

- src/components/StatementOfCashFlow/constants.ts
Changes order of cashflow statement line items and adds the cash at beginning of period section.
> change order of cashflow report line items

- src/components/Button/DownloadButton.tsx
- src/components/domain/transactions/searchField/transactionsSearchField.scss
- src/styles/button.scss
**Linear**: [LAY-1296](https://linear.app/layerfi/issue/LAY-1296/fix-misalignment-of-download-button-and-search-box-in-mobile-view)
The root cause of the issue is the use of a box-shadow. These look good, but they go outside of the border-box model - they  make UIs look misaligned. I think it is easier to manage box shadows if they only apply to interactions states (e.g. data-pressed).
This is a more questionable fix, as I am likely slightly changing the appearance of many secondary buttons across the app.
> [LAY-1296] fix: remove box shadow from secondary buttons

- src/components/BankTransactionRow/BankTransactionRow.tsx
- src/components/BankTransactionRow/SplitTooltipDetails.tsx
- src/types/bank_transactions.ts
We were seeing an error where a `categorization_status === SPLIT` and `category === null`.
> [LAY-1287] fix: a bank transaction can have a null category

- src/components/ui/Typography/money_text.scss
- src/styles/ledger_account.scss
- src/styles/table.scss
Root cause is that we set `--color-900: var(--color-dark)` (reference). This is a huge footgun that needs to be addressed more comprehensively.
> fix: temporarily revert color 900 -> 700

- src/components/domain/transactions/searchField/TransactionsSearchField.tsx
- src/components/domain/transactions/searchField/transactionsSearchField.scss
- src/components/ui/SearchField/minimalSearchField.scss
- src/styles/bank_transactions.scss
- src/styles/bank_transactions_mobile_list.scss
**Linear**: [LAY-1299](https://linear.app/layerfi/issue/LAY-1299/transactions-on-mobile-or-cards-and-search-box-are-not-aligned)
The bank transactions cards are arbitrarily fixed to a maximum width. This makes them makes them misaligned with their (flexible) header.
> [LAY-1299] fix: improve alignment of transaction card + header for mobile view

- src/api/layer.ts
- src/api/layer/bankTransactions.ts
- src/components/BankTransactions/BankTransactionsHeader.tsx
- src/hooks/useBankTransactions/useAugmentedBankTransactions.tsx
- src/hooks/useBankTransactions/useBankTransactions.ts
- src/hooks/useBankTransactions/useBankTransactionsDownload.ts
**Linear**: [LAY-1294](https://linear.app/layerfi/issue/LAY-1294/txn-export-not-respecting-search-filters-applied)
The download was not receiving any of the selected filters properly. This is still not a complete fix because the server does not respect all query parameters for a download.
> [LAY-1294] fix: downloading bank transactions should respect filters

- src/components/BookkeepingStatus/utils.tsx
- src/components/ExpandedBankTransactionRow/ExpandedBankTransactionRow.tsx
- src/components/JournalForm/JournalFormEntryLines.tsx
- src/components/MatchForm/MatchForm.tsx
- src/components/Tasks/TaskStatusBadge.tsx
- src/providers/GlobalDateStore/GlobalDateStoreProvider.tsx
- src/styles/bank_transactions.scss
- src/utils/bookkeeping/isCategorizationEnabled.ts
- src/utils/switch/assertUnreachable.ts
- src/utils/switch/safeAssertUnreachable.ts
**Linear**: [LAY-1295](https://linear.app/layerfi/issue/LAY-1295/fix-suggested-category-display-in-expanded-processing-row)
Bookkeeping users should not see extra information related to categorization.
> [LAY-1295] Hide suggested matches + suggested categorization when in bookkeeping mode

- package-lock.json
- package.json
- src/components/MatchForm/MatchForm.tsx
I made a mistake in [this commit](https://github.com/Layer-Fi/layer-react/pull/586/commits/d82065c282fbd35d8f7640507d18afd51b6cca0e) and was treating `categorizationEnabled` as the inverse.
> fix: direction of `categorizationEnabled` logic

- package-lock.json
- package.json
- src/components/Tasks/TasksList.tsx
This test needs to be tried in production mode.
> fix: prefer `id`-based keys in bookkeeping tasks

- package-lock.json
- package.json
- src/components/Tasks/TasksList.tsx
- src/components/Tasks/TasksListItem.tsx
- src/components/Tasks/TasksListMobile.tsx
This was an issue caused by [me over here](https://github.com/Layer-Fi/layer-react/pull/564/files#diff-dab11e5898b5c6ec9c07f30e72b6c3b4e1998b2d45a942462884218c06d37629L77-L87) on #564 (while fixing another bug).
We already display a sorted task list with incomplete tasks shown first. When we complete a task, we should expect some re-ordering... but going to the next page is nonsensical.
> fix: completing a task should not switch the page

- src/components/Tasks/TasksList.tsx
This look like an existing issue that [I carried over here](https://github.com/Layer-Fi/layer-react/pull/564/files#diff-dab11e5898b5c6ec9c07f30e72b6c3b4e1998b2d45a942462884218c06d37629L75-R52) in #564.
> fix: if there is no incomplete task on a page, none should default open

- src/components/Journal/download/JournalEntriesDownloadButton.tsx
- src/components/Journal/download/useJournalEntriesDownload.ts
- src/components/PeriodPicker/PeriodPicker.tsx
- src/components/PeriodPicker/index.tsx
1. Linting PeriodPicker
2. The `useSWRMutation`'s `error` is `any` in few places what violates [@typescript-eslint/no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment).
`BalanceSheetDownloadButton.tsx:`
> fix: error as any in swr responses and lint PeriodPicker

- src/components/Badge/Badge.tsx
- src/components/BankTransactionList/BankTransactionProcessingInfo.tsx
- src/components/Button/Button.tsx
- src/components/Button/SubmitButton.tsx
- src/components/Input/AmountInput.tsx
- src/components/Input/Input.tsx
- src/components/Input/InputWithBadge.tsx
- src/components/Input/MultiSelect.tsx
- src/components/Input/Select.tsx
- src/components/Tabs/Tab.tsx
- src/components/Textarea/Textarea.tsx
- src/components/Toggle/Toggle.tsx
- src/components/Typography/Text.tsx
- src/components/ui/Checkbox/Checkbox.tsx
`.Layer_tooltip` classname was explicitly provided to almost every use of `<TooltipContent />`.
The `feat/categorize-dropdown` branch moves `.Layer_tooltip` to the `TooltipContent`.
1. Remove `className='Layer__tooltip'` from everywhere except Tooltip
> refactor: clean up usage of Layer__tooltip classname

- src/components/LinkedAccountPill/LinkedAccountPill.tsx
- src/components/LinkedAccounts/ConfirmationModal/LinkedAccountsConfirmationModal.tsx
I was not properly respecting the dismissed state as overriding the other two statuses. This looks like a regression, as I've included this logic in the past.
> fix: regression in dismissing account confirmation modal

- package-lock.json
- package.json
I need to do a more robust audit of our dependencies, so I am starting with the simplest.
`npx npm-check-updates` can be used to get a sense of which packages are possible to upgrade.
> upgrade: patch version upgrades

- src/api/layer/categories.ts
- src/components/BankTransactionMobileList/BusinessCategories.tsx
- src/components/CategorySelect/CategorySelect.tsx
- src/components/JournalForm/JournalFormEntryLines.tsx
- src/contexts/LayerContext/LayerContext.tsx
- src/hooks/categories/useCategories.ts
- src/hooks/useChartOfAccounts/useCreateChildAccount.tsx
- src/providers/BusinessProvider/BusinessProvider.tsx
- src/types/layer_context.ts
This is a fast-follow to #602 which will invalidate any query tagged with `#categories`.
This is (technically) a breaking change because `useLayerContext` is exposed at the top-level. We are moving away from exposing hook and contexts at the top-level already.
> refactor!: decouple the default `categories` from the LayerContext

- src/api/layer/quickbooks.ts
- src/components/Quickbooks/Quickbooks.tsx
- src/hooks/useQuickbooks/useQuickbooks.ts
- src/types/quickbooks.ts
We added a new field to the `quickbooks/connection-status` API get the last time we synced with Quickbooks. This PR adds it to the API call, and returns this value from the `useQuickbooks` hook as `quickbooksLastSyncedAt`. 
Along the way, I refactored `useQuickbooks` to remove disabled lint rules around non-exhaustive `useEffect` dependencies and wrap all of the functions in `useCallback` so as to prevent them from causing unnecessary re-renders.
> feat: add `last_synced_at` field to `quickbooks/connection-status` fetcher

- src/components/ProfitAndLossChart/Indicator.tsx
- src/components/ProfitAndLossChart/ProfitAndLossChart.tsx
The animation logic in the `Indicator` component violates the rules of hooks. This causes a console error in dev mode - `React error: Expected static flag was missing` ([see issue](https://github.com/facebook/react/issues/24391)).
> fix: remove animation on chart `Indicator`

- package-lock.json
- package.json
- src/components/Integrations/IntegrationsQuickbooksItemThumb/IntegrationsQuickbooksItemThumbFooter.tsx
Fix a type error: `format` takes `number | date` and we were passing a `string`.
> fix: typecheck errors on `Integrations` component

- src/styles/profit_and_loss_detailed_charts.scss
I believe that the root cause of the issue is the use of `width: 100%`, but it is easier to force a grid layout and move on.
> fix: `Filters` label is partially cutoff

- src/styles/button.scss
This is a symptom of selector specificity being too low across the app. If we have any text, we need to be setting the `color` property as close as possible to the text.
> fix: text within a primary button needs a more specific selector

- src/api/layer.ts
- src/api/layer/bankTransactions.ts
- src/api/layer/linked_accounts.ts
- src/hooks/bookkeeping/periods/tasks/useDeleteUploadsOnTask.ts
- src/hooks/bookkeeping/periods/tasks/useSubmitResponseForTask.ts
- src/hooks/bookkeeping/periods/tasks/useUpdateTaskUploadDescription.ts
- src/hooks/bookkeeping/periods/tasks/useUploadDocumentsForTask.ts
- src/hooks/bookkeeping/useBankAccounts.ts
- src/hooks/business/useUpdateBusiness.ts
- src/hooks/businessPersonnel/useCreateBusinessPersonnel.ts
- src/hooks/businessPersonnel/useUpdateBusinessPersonnel.ts
- src/hooks/useBankTransactions/useAugmentedBankTransactions.tsx
- src/hooks/useBankTransactions/useBankTransactions.ts
- src/hooks/useBankTransactions/useCategorizeBankTransaction.ts
- src/hooks/useBankTransactions/useMatchBankTransaction.ts
- src/hooks/useBankTransactions/useUpdateBankTransactionMetadata.ts
- src/hooks/useChartOfAccounts/useCreateChildAccount.tsx
- src/hooks/useLinkedAccounts/useLinkedAccounts.ts
- src/hooks/useLinkedAccounts/useListExternalAccounts.ts
When we categorize or match a transaction, the ledger account balance at the top of the page should be updated to reflect the change.
> fix: revalidate {Bank|External}Accounts when categorizing or matching

- package-lock.json
- package.json
- src/hooks/useBankTransactions/useCategorizeBankTransaction.ts
I made a [bad change here](https://github.com/Layer-Fi/layer-react/pull/615/files#diff-8e8abec8c4e071254eb9be7d2bd419ed2463aa86cd0cb3e7d64af9f84cddf0eaR82) (autocomplete-related) on a previous PR.
> fix: categorization must invalidate bank account tags

- src/components/StatementOfCashFlow/datePicker/StatementOfCashFlowDatePicker.tsx
**Linear**: [LAY-1392](https://linear.app/layerfi/issue/LAY-1392/fix-date-selector-issue-for-statement-of-cash-flow)
The statement of cashflow `rangeDisplayMode` can be shifted to `dayRange` when the users moves the balance sheet date around. But, it can still be a `monthPicker` mode internally since this is the only allowed mode.
(See `ProfitAndLossDatePicker` for the [correct behavior](https://github.com/Layer-Fi/layer-react/blob/ea3616df3e30d5acaadf12243bb2d1b36d67850a/src/components/ProfitAndLossDatePicker/ProfitAndLossDatePicker.tsx#L35))
> [LAY-1392] fix: cashflow date picker behavior should match P&L date picker

- src/components/ProfitAndLossTable/ProfitAndLossTableComponent.tsx
**Linear**: [LAY-1391](https://linear.app/layerfi/issue/LAY-1391/remove-pie-chart-icons-from-specified-rows)
No Longer Expandable:
- Gross Profit
- Profit before Taxes
- Taxes
> [LAY-1391] fix: P&L table should not expand for several sections

- src/styles/view.scss
By arbitrarily increasing the z-index of our headings, we can interfere with items that are intended to overlap the header.
> fix: remove `z-index` on our view headers

- src/components/Input/AmountInput.tsx
- src/components/JournalForm/JournalFormEntryLines.tsx
- src/styles/inputs.scss
This PR fixes a bug where the "amount" input on the ledger entry form did not allow you to enter anything. 
I migrated from the `InputWithBadge` to the AmountInput` component that has stricter input validation around currency values so as to avoid converting values back and forth between numbers and currencies.
I also noticed some issues with tooltips appearing under the drawer due to z-index being less than the drawer, but will separate that work out into another PR because it has a much larger surface area.
See visual here:
> fix: broken "amount" input on ledger entry form

- .npmrc
This is a fast follow on an idea from @sarahraines. Now, when we publish "latest" versions, we need to explicitly specify the tag.
If you want to see all of the configuration (both defaults and overrides), try this:
```
npm config ls -l
```
> build: when publishing to npm, the default tag is "alpha"

- src/components/BankTransactions/BankTransactions.tsx
- src/components/BankTransactions/BankTransactionsHeader.tsx
- src/components/BankTransactions/BankTransactionsUploadMenu.tsx
- src/components/BankTransactions/BankTransactionsUploadModal/BankTransactionsUploadModal.tsx
- src/components/CsvUpload/CopyTemplateHeadersButtonGroup.tsx
- src/components/CsvUpload/ValidateCsvTable.tsx
- src/components/CsvUpload/csvUpload.scss
- src/components/LinkedAccounts/ConfirmationModal/LinkedAccountsConfirmationModal.tsx
- src/components/LinkedAccounts/OpeningBalanceModal/OpeningBalanceModal.tsx
- src/components/UploadTransactions/UploadTransactions.tsx
- src/components/UploadTransactions/UploadTransactionsUploadCsvStep.tsx
- src/components/UploadTransactions/uploadTransactions.scss
- src/components/domain/transactions/actions/TransactionsActions.tsx
- src/components/domain/transactions/actions/transactionsActions.scss
- src/components/domain/transactions/searchField/transactionsSearchField.scss
- src/components/ui/Button/Button.tsx
- src/components/ui/Button/button.scss
- src/components/ui/DropdownMenu/DropdownMenu.tsx
- src/index.tsx
- src/styles/bank_transactions.scss
- src/styles/internal_variables.scss
- src/views/BankTransactionsWithLinkedAccounts/BankTransactionsWithLinkedAccounts.tsx
This PR adds the CSV upload component in a menu that you can trigger from the bank transactions table. Along the way, I ended up doing some work on button styles to create relative parity between the old and new buttons.
> feat: add upload transactions by CSV to bank transactions header menu

- src/utils/swr/defaultSWRConfig.ts
For some reason, not revalidating on mount results in nothing loading 🙃 .
> fix: remove `revalidateOnMount: false`

- src/components/BaseConfirmationModal/BaseConfirmationModal.tsx
Uses the new `ModalTitleWithClose` component rather than a non-standard header for the new base confirmation modal.
> feat: use new `ModalTitleWithClose` in base confirmation modal

- src/components/ui/Button/button.scss
Fixes [LAY-1488](https://linear.app/layerfi/issue/LAY-1488/fix-hover-state-outline-for-txn-upload-button)
I think the ghost and outlined buttons should have the same hover state, even if it is more subtle for the outlined button.
> fix: delete outlined button special hover state

- package-lock.json
- package.json
- src/components/BankTransactions/BankTransactions.tsx
- src/views/BankTransactionsWithLinkedAccounts/BankTransactionsWithLinkedAccounts.tsx
I need to do a major revision on the `CustomerVendorSelector`. These changes effectively hide the current version behind a feature flag.
> fix: temporarily hide `CustomerVendorSelector`

- src/styles/bank_transactions.scss
Based on a discussion with Justin, we wanted to make the "Categorize" / "Category" section a bit smaller _and_ give more size to the account section.
These changes come at the expense of spacing for the transaction description.
> fix: second resizing of columns in bank transactions feed

- src/components/Tasks/tasks.scss
- src/styles/badge.scss
- src/styles/pagination.scss
- src/styles/variables.scss
This PR introduces 4 undefined CSS variables that must be explicitly set by the platform:
```
--bg-brand-primary
--fg-brand-primary
--bg-brand-accent
--fg-brand-accent
```
When these variables are set, they will override the use of `color-primary` (think: "dark") and `color-accent` (think: "light") in two (2) key areas:
- The hovered state of some solid buttons
- The default badge color
> fix: primary and accent color contrast

- src/features/bankTransactions/[bankTransactionId]/metadata/api/useSetMetadataOnBankTransaction.ts
- src/features/bankTransactions/[bankTransactionId]/tags/api/useRemoveTagFromBankTransaction.ts
- src/features/bankTransactions/[bankTransactionId]/tags/api/useTagBankTransaction.ts
- src/features/customers/api/useListCustomers.ts
- src/features/invoices/api/useListInvoices.tsx
- src/features/ledger/accounts/[ledgerAccountId]/api/useListLedgerAccountLines.ts
- src/features/ledger/entries/api/useListLedgerEntries.ts
- src/features/vendors/api/useListVendors.ts
- src/hooks/useBankTransactions/useBankTransactions.ts
- src/utils/swr/useGlobalInvalidator.ts
I may have made a mistake when I switched us over to `revalidateAll: true`, based on information from [this thread](https://github.com/vercel/swr/issues/1670#issuecomment-1625977770).
I believe we no longer need `revalidateAll: true` (and can `revalidateFirstPage: false`) because we are making an optimistic update in most situations.
However, the default assumption will be that we are _not_ doing an optimistic update, so we'll revalidate every page of an infinite query.
> fix: remove `revalidateAll` behavior from transactions SWR

- src/components/BalanceSheet/BalanceSheet.tsx
- src/components/BalanceSheet/index.tsx
- src/components/BalanceSheetDatePicker/BalanceSheetDatePicker.tsx
- src/components/ProfitAndLoss/ProfitAndLoss.tsx
- src/components/ProfitAndLossChart/ProfitAndLossChart.tsx
- src/components/ProfitAndLossCompareOptions/ProfitAndLossCompareOptions.tsx
- src/components/ProfitAndLossDatePicker/ProfitAndLossDatePicker.tsx
- src/components/ProfitAndLossReport/ProfitAndLossReport.tsx
- src/components/ProfitAndLossTable/ProfitAndLossCompareTable.tsx
- src/components/ProfitAndLossView/ProfitAndLossView.tsx
- src/components/StatementOfCashFlow/StatementOfCashFlow.tsx
- src/components/StatementOfCashFlow/datePicker/StatementOfCashFlowDatePicker.tsx
- src/components/StatementOfCashFlow/index.tsx
- src/hooks/useProfitAndLoss/useProfitAndLoss.tsx
- src/hooks/useProfitAndLossComparison/useProfitAndLossComparison.tsx
- src/index.tsx
- src/providers/GlobalDateStore/GlobalDateStoreProvider.tsx
- src/providers/GlobalDateStore/useGlobalDateRangePicker.ts
- src/providers/ReportsModeStoreProvider/ReportsModeStoreProvider.tsx
- src/views/Reports/Reports.tsx
This PR fixes the date picker so that it honors defaults passed by the platform for P&L and SOCF.
It also makes the following design changes:
1. [Old] All dates are still global, and all date pickers still set the global state.
2. [New] What is _shown_ on the date picker is what is filtered. E.g., if the global date range is 4/15-4/29 but a month picker is shown, then the effective date range on that view is 4/1-4/30.
3. [New] If you navigate away from a report, we remember what mode you were on for that report. E.g., if you are looking at a month picker on P&L and then go to a date picker on SOCF, going back to P&L shows the month picker again.
> fix: date picker respects default

- src/components/Integrations/Integrations.tsx
- src/components/LinkedAccounts/LinkedAccounts.tsx
- src/views/AccountingOverview/AccountingOverview.tsx
- src/views/BankTransactionsWithLinkedAccounts/BankTransactionsWithLinkedAccounts.tsx
- src/views/BookkeepingOverview/BookkeepingOverview.tsx
This PR makes it so the default behavior for any section within a view is that it is _not_ elevated (no drop shadow). We still respect when the `elevated` prop is passed by platform customers (e.g., for linked accounts), but will deprecate this in components v0.2.0.
https://linear.app/layerfi/issue/LAY-1539/remove-drop-shadow-from-pandl-chart-and-bank-accounts-components
> Remove default elevated behavior on views and sections within views

- src/components/Invoices/InvoiceForm/useInvoiceForm.ts
- src/utils/bigDecimalUtils.ts
Cannot publish to npm unless we use the `BigInt` constructor rather than BigInt literals. This is because our package compilation target is es2016 to support older clients and browsers, but BigInt literals were not introduced until es2020.
> fix: Cannot use `BigInt` literals due to es2016 compilation target for npm

- src/providers/GlobalDateStore/GlobalDateStoreProvider.tsx
If you select an arbitrary date on the balance sheet (e.g., 2/9), set the global date range to be from the beginning of the same month (e.g., 2/1-2/9) rather than just the single day.
https://layer-financial.slack.com/archives/C06KH7QKS6M/p1753813475803499?thread_ts=1753812311.466079&cid=C06KH7QKS6M
> fix: Set date range from beginning of month on balance sheet date select

- src/styles/panel.scss
Like #699, but down to `z-index: 10` for Dripos who has popovers at 20.
> fix: Reduce z-index on sidebar (again)

- package-lock.json
- package.json
- src/components/Invoices/InvoiceForm/InvoiceForm.tsx
- src/components/Invoices/InvoiceForm/invoiceForm.scss
- src/components/Invoices/InvoiceForm/useInvoiceForm.ts
- src/components/Invoices/InvoiceForm/utils.ts
- src/components/Invoices/InvoiceTermsComboBox/InvoiceTermsComboBox.tsx
- src/components/ui/Date/Date.scss
- src/components/ui/Date/Date.tsx
- src/components/ui/Form/form.scss
- src/components/ui/Input/input.scss
- src/components/ui/index.scss
- src/features/forms/components/BaseFormTextField.tsx
- src/features/forms/components/FormBigDecimalField.tsx
- src/features/forms/components/FormCheckboxField.tsx
- src/features/forms/components/FormDateField.tsx
- src/features/forms/components/FormTextAreaField.tsx
- src/features/forms/components/FormTextField.tsx
- src/features/forms/hooks/useForm.tsx
- src/features/forms/types.ts
- src/features/invoices/invoiceSchemas.ts
- src/utils/schema/utils.ts
- src/utils/time/timeUtils.ts
1. Creates a canonical DateField for the form, as well as implements two date fields for sent/due date.
2. Implements a terms dropdown that affects the date fields (e.g., net 10, net 30, etc.)
3. Adds an invoice number field.
4. Adds `@internationalized/date` as a dependency, and upgrades `@tanstack/react-form`
5. Creates an `InvoiceForm` schema that will help us down the road with converting the form to an API request
6. Fixes some infinite recursion issues with form validation.
> feat: create date, invoice no, invoice terms fields

- src/components/CsvUpload/DownloadCsvTemplateButton.tsx
- src/components/JournalForm/JournalFormEntryLines.tsx
- src/components/UploadTransactions/UploadTransactionsUploadCsvStep.tsx
- src/components/UploadTransactions/UploadTransactionsValidateCsvStep.tsx
- src/components/UploadTransactions/template.ts
- src/contexts/ChartOfAccountsContext/ChartOfAccountsContext.tsx
Fixes: LAY-1572
Include optional fields in example csv 
[upload_transactions (3).csv](https://github.com/user-attachments/files/21692714/upload_transactions.3.csv)
> Include optional fields in example csv

- src/components/Invoices/InvoiceForm/InvoiceForm.tsx
- src/components/Invoices/InvoiceForm/formUtils.ts
- src/features/forms/components/FormBigDecimalField.tsx
- src/features/invoices/invoiceSchemas.ts
- src/hooks/usePaginationRange/usePaginationRange.ts
[LAY-1569](https://linear.app/layerfi/issue/LAY-1569/rename-tax-checkbox-to-taxable-for-clarity)
[LAY-1575](https://linear.app/layerfi/issue/LAY-1575/pagination-bar-re-inserts-numbers-upon-new-fetches)
[LAY-1577](https://linear.app/layerfi/issue/LAY-1577/trim-invoice-text-fields-before-validation)
> fix: resolve invoices demo testing bugs

- package-lock.json
- package.json
- src/components/Bills/useBillForm.ts
- src/components/BusinessForm/useBusinessForm.ts
- src/components/CustomAccountForm/useCustomAccountForm.ts
- src/components/Invoices/InvoiceDetail/InvoiceDetail.tsx
- src/components/Invoices/InvoiceForm/InvoiceForm.tsx
- src/components/Invoices/InvoiceForm/formUtils.ts
- src/components/Invoices/InvoiceForm/useInvoiceForm.ts
- src/features/forms/hooks/useForm.tsx
See commit messages for the incremental fixes. The main upshot:
1. Strip empty line items out of invoice creation request
2. Require that invoice due date is at/after creation date
3. Show API submission errors in addition to just form validation errors at top of form
4. Show toast on invoice creation/update success
5. Update validation logic ensure that we only revalidate on form submit (rather than field blur/change)
6. Upgrade TanStack Form to unlock new functionality needed for (5), and update types to match.
> fix: another batch of invoice form fixes

- src/styles/datepicker.scss
Datepicker contents is no longer truncated by container at any zoom level.
> fix: datepicker width to 24ch

- src/components/BankTransactions/BankTransactions.tsx
- src/components/BankTransactions/BankTransactionsHeader.tsx
- src/contexts/BankTransactionsContext/BankTransactionsContext.tsx
- src/hooks/useBankTransactions/types.ts
- src/hooks/useBankTransactions/useAugmentedBankTransactions.tsx
This PR adds a new `applyGlobalDateRange` prop to the `BankTransactions` component that applies the current global month (e.g., selected in the overview component) to the list of bank txns.
> feat: filter bank txns on global date range

- src/components/Invoices/InvoiceDetail/InvoiceDetailHeaderMenu.tsx
- src/components/Invoices/Modal/InvoiceResetModal.tsx
- src/features/invoices/api/useResetInvoice.tsx
This PR wires up the new `/invoices/${invoiceId}/reset` endpoint to the frontend to allow end users to kick their invoices back to a "SENT" status by deleting payments, refunds, writeoffs, etc. and unvoiding.
> feat: reset invoices

- src/views/AccountingOverview/internal/TransactionsToReview.tsx
Needed to actively go fetch a new P&L monthly summaries when we switch months and don't have the correct data to calculate the number of transactions to review. In the meantime, we show a loading state.
> fix: load correct number of txns to review for each month

- src/components/Invoices/InvoiceForm/formUtils.ts
Invoice line item sales taxes were being calculated incorrectly because I forgot to subtract out the discount rate before applying the sales tax percentage.
> fix: invoice sales taxes calculation

- src/components/BankTransactionMobileList/BankTransactionMobileListItem.tsx
- src/components/CategorySelect/CategorySelect.tsx
- src/components/MatchForm/MatchForm.tsx
- src/components/MatchForm/MatchFormMobile.tsx
- src/index.tsx
- src/schemas/match.ts
- Add export for EntityName enum. Useful for switch statements while linking so people can do stuff like have different logic for invoice payments vs bank transactions etc.
- Fix bug where we weren't decoding match details schema
> export entity name, fix parsing match details schema

- src/components/ui/ComboBox/ComboBox.tsx
- src/components/ui/ListBox/ListBox.tsx
- src/schemas/bankTransactions/bankTransaction.ts
- src/schemas/bankTransactions/base.ts
- src/schemas/bankTransactions/categorizationRules/categorizationRule.ts
This PR fixes a bug with `react-aria-components` and our combobox where when the React Aria modal is shown, the combobox is no longer interactive because it is "inert." This new property tells React Aria to chill out.
Also fixed a circular dependency issue with new schemas.
> fix: dropdown issue for BrightGo

- src/components/CategorySelect/CategorySelect.tsx
Change "match" tag to "transfer" in the bank transaction feed
[LAY-1763](https://linear.app/layerfi/issue/LAY-1763/change-match-tag-to-transfer-in-the-bank-transaction-feed)
* 'Match' --> 'Transfer' when the match is identified as a transfer between accounts
* 'Match' --> 'Transfer' in the dropdown, when all matches are transfers between accounts
Note: There's a possible case with multiple matches, current implementation will only show "Transfer" as the dropdown category if they're all Transfer. If we're expecting multiple matches with some being Transfer and some being non-Transfer to be a frequent occurrence, will need to update.
> Change "match" tag to "transfer" in the bank transaction feed
